In [98]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
from statsmodels.tsa.arima.model import ARIMA

In [122]:
df = pd.read_csv('Salest1.csv')
df

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,11/26/2013,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
1,11/26/2015,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
2,3/23/2014,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45.0,120.0,1366.0,1035.0,2401.0
3,3/23/2016,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45.0,120.0,1188.0,900.0,2088.0
4,5/15/2014,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45.0,120.0,238.0,180.0,418.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7644,6/14/2014,14,June,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,15,2.0,5.0,42.0,30.0,72.0
7645,6/14/2014,14,June,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,10,2.0,5.0,28.0,20.0,48.0
7646,6/14/2016,14,June,2016,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,17,2.0,5.0,48.0,34.0,82.0
7647,6/14/2016,14,June,2016,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,11,2.0,5.0,31.0,22.0,53.0
7648,6/17/2014,17,June,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,6,2.0,5.0,NaN,NaN,NaN

In [27]:
df.head(10)

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,11/26/2013,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
1,11/26/2015,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
2,3/23/2014,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45.0,120.0,1366.0,1035.0,2401.0
3,3/23/2016,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45.0,120.0,1188.0,900.0,2088.0
4,5/15/2014,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45.0,120.0,238.0,180.0,418.0
5,5/15/2016,15,May,2016,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,5,45.0,120.0,297.0,225.0,522.0
6,5/22/2014,22,May,2014,47,Adults (35-64),F,Australia,Victoria,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45.0,120.0,199.0,180.0,379.0
7,5/22/2016,22,May,2016,47,Adults (35-64),F,Australia,Victoria,Accessories,Bike Racks,Hitch Rack - 4-Bike,2,45.0,120.0,100.0,90.0,190.0
8,2/22/2014,22,February,2014,35,Adults (35-64),M,Australia,Victoria,Accessories,Bike Racks,Hitch Rack - 4-Bike,22,45.0,120.0,1096.0,990.0,2086.0
9,2/22/2016,22,February,2016,35,Adults (35-64),M,Australia,Victoria,Accessories,Bike Racks,Hitch Rack - 4-Bike,21,45.0,120.0,1046.0,945.0,1991.0

In [100]:
df.shape

(7649, 18)

In [110]:
df["Date"]

0       11/26/2013
1       11/26/2015
2        3/23/2014
3        3/23/2016
4        5/15/2014
           ...
7644     6/14/2014
7645     6/14/2014
7646     6/14/2016
7647     6/14/2016
7648     6/17/2014
Name: Date, Length: 7649, dtype: object

In [112]:
df[df["Date"]==11/26/2015].Product_Category

Series([], Name: Product_Category, dtype: object)

In [115]:
df["Sub_Category"]

0              Bike Racks
1              Bike Racks
2              Bike Racks
3              Bike Racks
4              Bike Racks
              ...
7644    Bottles and Cages
7645    Bottles and Cages
7646    Bottles and Cages
7647    Bottles and Cages
7648    Bottles and Cages
Name: Sub_Category, Length: 7649, dtype: object

In [120]:
df[df["Sub_Category"]==11/26/2015].Revenue

Series([], Name: Revenue, dtype: float64)

In [129]:
df[(df.Product_Category=="Accessories") & (df.Cost>90)]

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,11/26/2013,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
1,11/26/2015,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
2,3/23/2014,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45.0,120.0,1366.0,1035.0,2401.0
3,3/23/2016,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45.0,120.0,1188.0,900.0,2088.0
4,5/15/2014,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45.0,120.0,238.0,180.0,418.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7191,5/12/2016,12,May,2016,43,Adults (35-64),F,United States,Washington,Accessories,Bottles and Cages,Mountain Bottle Cage,27,4.0,10.0,103.0,108.0,211.0
7478,4/14/2014,14,April,2014,29,Young Adults (25-34),F,France,Seine Saint Denis,Accessories,Bottles and Cages,Mountain Bottle Cage,26,4.0,10.0,109.0,104.0,213.0
7479,4/14/2016,14,April,2016,29,Young Adults (25-34),F,France,Seine Saint Denis,Accessories,Bottles and Cages,Mountain Bottle Cage,27,4.0,10.0,113.0,108.0,221.0
7516,6/11/2014,11,June,2014,35,Adults (35-64),F,France,Seine (Paris),Accessories,Bottles and Cages,Mountain Bottle Cage,25,4.0,10.0,105.0,100.0,205.0
7518,6/11/2016,11,June,2016,35,Adults (35-64),F,France,Seine (Paris),Accessories,Bottles and Cages,Mountain Bottle Cage,25,4.0,10.0,105.0,100.0,205.0

#select a column from data

In [28]:
df['Month']

0       November
1       November
2          March
3          March
4            May
          ...
7644        June
7645        June
7646        June
7647        June
7648        June
Name: Month, Length: 7649, dtype: object

#select the first row 

index based selection.

In [29]:
df.iloc[0,:]

Date                         11/26/2013
Day                                  26
Month                          November
Year                               2013
Customer_Age                         19
Age_Group                   Youth (<25)
Customer_Gender                       M
Country                          Canada
State                  British Columbia
Product_Category            Accessories
Sub_Category                 Bike Racks
Product             Hitch Rack - 4-Bike
Order_Quantity                        8
Unit_Cost                          45.0
Unit_Price                        120.0
Profit                            590.0
Cost                              360.0
Revenue                           950.0
Name: 0, dtype: object

# select the first coulmn

In [30]:
df.iloc[:,0]

0       11/26/2013
1       11/26/2015
2        3/23/2014
3        3/23/2016
4        5/15/2014
           ...
7644     6/14/2014
7645     6/14/2014
7646     6/14/2016
7647     6/14/2016
7648     6/17/2014
Name: Date, Length: 7649, dtype: object

# select the firt 3 rows

In [31]:
df.iloc[:3, :]

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,11/26/2013,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
1,11/26/2015,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
2,3/23/2014,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45.0,120.0,1366.0,1035.0,2401.0

# select the last column

In [32]:
df.iloc [: , -1]

0        950.0
1        950.0
2       2401.0
3       2088.0
4        418.0
         ...
7644      72.0
7645      48.0
7646      82.0
7647      53.0
7648       NaN
Name: Revenue, Length: 7649, dtype: float64

# fancy indexing
-> indexs is a list
select row 1 ,50 ,5

In [33]:
df.iloc[[1,5,50], :]

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
1,11/26/2015,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
5,5/15/2016,15,May,2016,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,5,45.0,120.0,297.0,225.0,522.0
50,7/15/2013,15,July,2013,52,Adults (35-64),F,France,Seine Saint Denis,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,427.0,360.0,787.0

# select the last 10 rows

In [34]:
df.iloc [:-10 , :]

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,11/26/2013,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
1,11/26/2015,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
2,3/23/2014,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45.0,120.0,1366.0,1035.0,2401.0
3,3/23/2016,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45.0,120.0,1188.0,900.0,2088.0
4,5/15/2014,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45.0,120.0,238.0,180.0,418.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7634,4/25/2016,25,April,2016,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,30,2.0,5.0,84.0,60.0,144.0
7635,4/25/2016,25,April,2016,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,2,2.0,5.0,6.0,4.0,10.0
7636,5/3/2014,3,May,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,7,2.0,5.0,20.0,14.0,34.0
7637,5/3/2014,3,May,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,14,2.0,5.0,39.0,28.0,67.0
7638,5/3/2016,3,May,2016,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,6,2.0,5.0,17.0,12.0,29.0

# label based selection

In [35]:
df.loc[:, ['Day','Date','Month' ]]

      Day        Date     Month
0      26  11/26/2013  November
1      26  11/26/2015  November
2      23   3/23/2014     March
3      23   3/23/2016     March
4      15   5/15/2014       May
...   ...         ...       ...
7644   14   6/14/2014      June
7645   14   6/14/2014      June
7646   14   6/14/2016      June
7647   14   6/14/2016      June
7648   17   6/17/2014      June

[7649 rows x 3 columns]

In [36]:
df.iloc[1:4]

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
1,11/26/2015,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
2,3/23/2014,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45.0,120.0,1366.0,1035.0,2401.0
3,3/23/2016,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45.0,120.0,1188.0,900.0,2088.0

In [37]:
df.loc[1:4]

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
1,11/26/2015,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
2,3/23/2014,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45.0,120.0,1366.0,1035.0,2401.0
3,3/23/2016,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45.0,120.0,1188.0,900.0,2088.0
4,5/15/2014,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45.0,120.0,238.0,180.0,418.0

In [38]:
df1 =df.set_index("Day")
df1

,Date,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
Day,,,,,,,,,,,,,,,,,
26,11/26/2013,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
26,11/26/2015,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
23,3/23/2014,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45.0,120.0,1366.0,1035.0,2401.0
23,3/23/2016,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45.0,120.0,1188.0,900.0,2088.0
15,5/15/2014,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45.0,120.0,238.0,180.0,418.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14,6/14/2014,June,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,15,2.0,5.0,42.0,30.0,72.0
14,6/14/2014,June,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,10,2.0,5.0,28.0,20.0,48.0
14,6/14/2016,June,2016,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,17,2.0,5.0,48.0,34.0,82.0
14,6/14/2016,June,2016,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,11,2.0,5.0,31.0,22.0,53.0
17,6/17/2014,June,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,6,2.0,5.0,NaN,NaN,NaN

In [39]:
df1.iloc[0:3 ,:]

,Date,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
Day,,,,,,,,,,,,,,,,,
26,11/26/2013,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
26,11/26/2015,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
23,3/23/2014,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45.0,120.0,1366.0,1035.0,2401.0

# conditional selection

# Have a look at the saled products in Canada

In [40]:
df.Country

0               Canada
1               Canada
2            Australia
3            Australia
4            Australia
             ...
7644    United Kingdom
7645    United Kingdom
7646    United Kingdom
7647    United Kingdom
7648    United Kingdom
Name: Country, Length: 7649, dtype: object

In [41]:
df.Country =='Canada'

0        True
1        True
2       False
3       False
4       False
        ...
7644    False
7645    False
7646    False
7647    False
7648    False
Name: Country, Length: 7649, dtype: bool

In [42]:
df.loc[df.Country =='Canada']

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,11/26/2013,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
1,11/26/2015,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
16,9/2/2013,2,September,2013,29,Young Adults (25-34),M,Canada,NaN,Accessories,Bike Racks,Hitch Rack - 4-Bike,2,45.0,120.0,148.0,90.0,238.0
17,9/2/2015,2,September,2015,29,Young Adults (25-34),M,Canada,NaN,Accessories,Bike Racks,NaN,1,45.0,120.0,74.0,45.0,119.0
18,1/22/2014,22,January,2014,29,Young Adults (25-34),M,Canada,NaN,Accessories,Bike Racks,NaN,1,45.0,120.0,74.0,45.0,119.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7315,2/10/2016,10,February,2016,55,Adults (35-64),F,Canada,British Columbia,Accessories,Bottles and Cages,Water Bottle - 30 oz.,15,2.0,5.0,44.0,30.0,74.0
7316,2/21/2014,21,February,2014,55,Adults (35-64),F,Canada,British Columbia,Accessories,Bottles and Cages,Water Bottle - 30 oz.,10,2.0,5.0,30.0,20.0,50.0
7317,2/21/2016,21,February,2016,55,Adults (35-64),F,Canada,British Columbia,Accessories,Bottles and Cages,Water Bottle - 30 oz.,10,2.0,5.0,30.0,20.0,50.0
7318,2/23/2014,23,February,2014,55,Adults (35-64),F,Canada,British Columbia,Accessories,Bottles and Cages,Water Bottle - 30 oz.,17,2.0,5.0,50.0,34.0,84.0
7319,2/23/2016,23,February,2016,55,Adults (35-64),F,Canada,British Columbia,Accessories,Bottles and Cages,Water Bottle - 30 oz.,19,2.0,5.0,56.0,38.0,94.0

# have a look at the Products that have a cost above the average

In [43]:
df.Cost

0        360.0
1        360.0
2       1035.0
3        900.0
4        180.0
         ...
7644      30.0
7645      20.0
7646      34.0
7647      22.0
7648       NaN
Name: Cost, Length: 7649, dtype: float64

In [44]:
df.Cost < df['Cost'].mean()

0       False
1       False
2       False
3       False
4       False
        ...
7644     True
7645     True
7646     True
7647     True
7648    False
Name: Cost, Length: 7649, dtype: bool

In [45]:
df.loc[df.Cost < df['Cost'].mean()]

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
17,9/2/2015,2,September,2015,29,Young Adults (25-34),M,Canada,NaN,Accessories,Bike Racks,NaN,1,45.0,120.0,74.0,45.0,119.0
18,1/22/2014,22,January,2014,29,Young Adults (25-34),M,Canada,NaN,Accessories,Bike Racks,NaN,1,45.0,120.0,74.0,45.0,119.0
19,1/22/2016,22,January,2016,29,Young Adults (25-34),M,Canada,NaN,Accessories,Bike Racks,NaN,1,45.0,NaN,74.0,45.0,119.0
25,8/25/2015,25,August,2015,49,Adults (35-64),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,1,45.0,NaN,NaN,45.0,119.0
45,8/27/2015,27,August,2015,57,Adults (35-64),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,1,45.0,120.0,74.0,45.0,119.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7643,6/7/2016,7,June,2016,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,15,2.0,5.0,42.0,30.0,72.0
7644,6/14/2014,14,June,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,15,2.0,5.0,42.0,30.0,72.0
7645,6/14/2014,14,June,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,10,2.0,5.0,28.0,20.0,48.0
7646,6/14/2016,14,June,2016,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,17,2.0,5.0,48.0,34.0,82.0
7647,6/14/2016,14,June,2016,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,11,2.0,5.0,31.0,22.0,53.0

In [46]:
(df.Country =='Canada') & (df.Cost < df['Cost'].mean() )

0       False
1       False
2       False
3       False
4       False
        ...
7644    False
7645    False
7646    False
7647    False
7648    False
Length: 7649, dtype: bool

In [52]:
model = ARIMA(df['Cost'], order=(5,1,0))
model_fit = model.fit()

# عرض تقديرات الموديل
print(model_fit.summary())

# التنبؤ بالمبيعات في المستقبل
forecast = model_fit.forecast(steps=12)
print(forecast)

                               SARIMAX Results
==============================================================================
Dep. Variable:                   Cost   No. Observations:                 7649
Model:                 ARIMA(5, 1, 0)   Log Likelihood              -45056.273
Date:                Wed, 22 May 2024   AIC                          90124.545
Time:                        21:43:12   BIC                          90166.199
Sample:                             0   HQIC                         90138.835
                               - 7649
Covariance Type:                  opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
ar.L1         -0.2711      0.007    -41.253      0.000      -0.284      -0.258
ar.L2         -0.5420      0.003   -166.430      0.000      -0.548      -0.536
ar.L3         -0.2755      0.008    -35.804      0.000      -0.291      -0.260
ar.L4         -0.2547      0.003    -81.906      0.000      -0.261      -0.249
ar.L5         -0.1493      0.007    -21.920      0.000      -0.163      -0.136
sigma2      7677.5242     29.512    260.153      0.000    7619.683    7735.366
===================================================================================
Ljung-Box (L1) (Q):                   1.43   Jarque-Bera (JB):            439823.68
Prob(Q):                              0.23   Prob(JB):                         0.00
Heteroskedasticity (H):               0.05   Skew:                             2.22
Prob(H) (two-sided):                  0.00   Kurtosis:                        39.88
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
7649    24.518246
7650    26.063593
7651    24.267361
7652    24.938735
7653    24.276441
7654    23.269188
7655    23.942924
7656    24.585915
7657    24.392381
7658    24.266196
7659    24.206976
7660    24.080353
Name: predicted_mean, dtype: float64

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7649 entries, 0 to 7648
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              7649 non-null   object
 1   Day               7649 non-null   int64
 2   Month             7649 non-null   object
 3   Year              7649 non-null   int64
 4   Customer_Age      7649 non-null   int64
 5   Age_Group         7649 non-null   object
 6   Customer_Gender   7649 non-null   object
 7   Country           7644 non-null   object
 8   State             7640 non-null   object
 9   Product_Category  7649 non-null   object
 10  Sub_Category      7649 non-null   object
 11  Product           7642 non-null   object
 12  Order_Quantity    7649 non-null   int64
 13  Unit_Cost         7645 non-null   float64
 14  Unit_Price        7642 non-null   float64
 15  Profit            7642 non-null   float64
 16  Cost              7648 non-null   float64
 17  Revenue           7648 non-null   float64
dtypes: float64(5), int64(4), object(9)
memory usage: 1.1+ MB

In [55]:
df.describe(include='O')

,Date,Month,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product
count,7649,7649,7649,7649,7644,7640,7649,7649,7642
unique,774,12,4,2,6,39,1,3,5
top,9/13/2013,June,Adults (35-64),M,United States,California,Accessories,Bottles and Cages,Water Bottle - 30 oz.
freq,27,805,3826,3976,2496,1346,7649,6601,4403

In [56]:
df.Customer_Age.max()

87

In [57]:
df.Customer_Age.min()

17

In [58]:
df.Revenue.describe()

count    7648.000000
mean      190.986140
std       347.698752
min         4.000000
25%        47.000000
50%        95.000000
75%       149.000000
max      3564.000000
Name: Revenue, dtype: float64

In [59]:
df.drop(['Date'] , axis=1, inplace=True) #drop Day coloum
df.head(5)

,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
1,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
2,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45.0,120.0,1366.0,1035.0,2401.0
3,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45.0,120.0,1188.0,900.0,2088.0
4,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45.0,120.0,238.0,180.0,418.0

In [60]:
df_indexed = df.set_index('Country') #search by colom as index
result = df_indexed.loc["Canada"]
print(result)

         Day      Month  Year  Customer_Age             Age_Group  \
Country
Canada    26   November  2013            19           Youth (<25)
Canada    26   November  2015            19           Youth (<25)
Canada     2  September  2013            29  Young Adults (25-34)
Canada     2  September  2015            29  Young Adults (25-34)
Canada    22    January  2014            29  Young Adults (25-34)
...      ...        ...   ...           ...                   ...
Canada    10   February  2016            55        Adults (35-64)
Canada    21   February  2014            55        Adults (35-64)
Canada    21   February  2016            55        Adults (35-64)
Canada    23   February  2014            55        Adults (35-64)
Canada    23   February  2016            55        Adults (35-64)

        Customer_Gender             State Product_Category       Sub_Category  \
Country
Canada                M  British Columbia      Accessories         Bike Racks
Canada                M  British Columbia      Accessories         Bike Racks
Canada                M               NaN      Accessories         Bike Racks
Canada                M               NaN      Accessories         Bike Racks
Canada                M               NaN      Accessories         Bike Racks
...                 ...               ...              ...                ...
Canada                F  British Columbia      Accessories  Bottles and Cages
Canada                F  British Columbia      Accessories  Bottles and Cages
Canada                F  British Columbia      Accessories  Bottles and Cages
Canada                F  British Columbia      Accessories  Bottles and Cages
Canada                F  British Columbia      Accessories  Bottles and Cages

                       Product  Order_Quantity  Unit_Cost  Unit_Price  Profit  \
Country
Canada     Hitch Rack - 4-Bike               8       45.0       120.0   590.0
Canada     Hitch Rack - 4-Bike               8       45.0       120.0   590.0
Canada     Hitch Rack - 4-Bike               2       45.0       120.0   148.0
Canada                     NaN               1       45.0       120.0    74.0
Canada                     NaN               1       45.0       120.0    74.0
...                        ...             ...        ...         ...     ...
Canada   Water Bottle - 30 oz.              15        2.0         5.0    44.0
Canada   Water Bottle - 30 oz.              10        2.0         5.0    30.0
Canada   Water Bottle - 30 oz.              10        2.0         5.0    30.0
Canada   Water Bottle - 30 oz.              17        2.0         5.0    50.0
Canada   Water Bottle - 30 oz.              19        2.0         5.0    56.0

          Cost  Revenue
Country
Canada   360.0    950.0
Canada   360.0    950.0
Canada    90.0    238.0
Canada    45.0    119.0
Canada    45.0    119.0
...        ...      ...
Canada    30.0     74.0
Canada    20.0     50.0
Canada    20.0     50.0
Canada    34.0     84.0
Canada    38.0     94.0

[1288 rows x 16 columns]

In [61]:
df.iloc[1,:7]

Day                         26
Month                 November
Year                      2015
Customer_Age                19
Age_Group          Youth (<25)
Customer_Gender              M
Country                 Canada
Name: 1, dtype: object

In [62]:
df.sort_values(by=["Customer_Age"] ,ascending=True)

,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
6211,28,February,2016,17,Youth (<25),M,Canada,British Columbia,Accessories,Bottles and Cages,Water Bottle - 30 oz.,4,2.0,5.0,12.0,8.0,20.0
2590,27,December,2013,17,Youth (<25),F,France,Seine Saint Denis,Accessories,Bottles and Cages,Water Bottle - 30 oz.,12,2.0,5.0,25.0,24.0,49.0
2591,27,December,2013,17,Youth (<25),F,France,Seine Saint Denis,Accessories,Bottles and Cages,Water Bottle - 30 oz.,20,2.0,5.0,42.0,40.0,82.0
2593,27,December,2015,17,Youth (<25),F,France,Seine Saint Denis,Accessories,Bottles and Cages,Water Bottle - 30 oz.,22,2.0,5.0,46.0,44.0,90.0
6215,16,March,2016,17,Youth (<25),M,Canada,British Columbia,Accessories,Bottles and Cages,Water Bottle - 30 oz.,12,2.0,5.0,35.0,24.0,59.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1652,11,June,2014,73,Seniors (64+),F,Canada,British Columbia,Accessories,Bottles and Cages,Mountain Bottle Cage,1,4.0,10.0,6.0,4.0,10.0
812,25,May,2014,84,Seniors (64+),F,United Kingdom,England,Accessories,Bike Stands,All-Purpose Bike Stand,5,59.0,159.0,468.0,295.0,763.0
813,25,May,2016,84,Seniors (64+),F,United Kingdom,England,Accessories,Bike Stands,All-Purpose Bike Stand,5,59.0,159.0,468.0,295.0,763.0
135,19,February,2016,87,Seniors (64+),F,Germany,Saarland,Accessories,Bike Racks,Hitch Rack - 4-Bike,3,45.0,120.0,160.0,135.0,295.0
134,19,February,2014,87,Seniors (64+),F,Germany,Saarland,Accessories,Bike Racks,Hitch Rack - 4-Bike,2,45.0,120.0,107.0,90.0,197.0

In [78]:
df[df.duplicated()]

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
1021,12/19/2013,19,December,2013,22,Youth (<25),M,Australia,New South Wales,Accessories,Bike Stands,All-Purpose Bike Stand,9,59.0,159.0,714.0,531.0,1245.0
1091,9/30/2015,30,September,2015,42,Adults (35-64),F,Australia,Victoria,Accessories,Bottles and Cages,Mountain Bottle Cage,5,4.0,10.0,20.0,20.0,40.0
1093,10/24/2013,24,October,2013,42,Adults (35-64),F,Australia,Victoria,Accessories,Bottles and Cages,Mountain Bottle Cage,2,4.0,10.0,8.0,8.0,16.0
1095,10/24/2015,24,October,2015,42,Adults (35-64),F,Australia,Victoria,Accessories,Bottles and Cages,Mountain Bottle Cage,1,4.0,10.0,4.0,4.0,8.0
1193,1/15/2016,15,January,2016,42,Adults (35-64),M,France,Seine Saint Denis,Accessories,Bottles and Cages,Water Bottle - 30 oz.,14,2.0,5.0,29.0,28.0,57.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7223,9/22/2015,22,September,2015,60,Adults (35-64),M,Canada,British Columbia,Accessories,Bottles and Cages,Water Bottle - 30 oz.,12,2.0,5.0,35.0,24.0,59.0
7401,4/21/2014,21,April,2014,33,Young Adults (25-34),M,United States,Washington,Accessories,Bottles and Cages,Water Bottle - 30 oz.,18,2.0,5.0,34.0,36.0,70.0
7461,11/15/2015,15,November,2015,28,Young Adults (25-34),M,Germany,Hamburg,Accessories,Bottles and Cages,Road Bottle Cage,22,3.0,9.0,118.0,66.0,184.0
7593,3/26/2014,26,March,2014,38,Adults (35-64),M,Germany,Bayern,Accessories,Bottles and Cages,Road Bottle Cage,12,3.0,9.0,71.0,36.0,107.0
7595,3/26/2016,26,March,2016,38,Adults (35-64),M,Germany,Bayern,Accessories,Bottles and Cages,Road Bottle Cage,12,3.0,9.0,71.0,36.0,107.0

In [65]:
df.isna().sum()

Day                 0
Month               0
Year                0
Customer_Age        0
Age_Group           0
Customer_Gender     0
Country             5
State               9
Product_Category    0
Sub_Category        0
Product             7
Order_Quantity      0
Unit_Cost           4
Unit_Price          7
Profit              7
Cost                1
Revenue             1
dtype: int64

In [72]:
n_df=df.Profit .fillna(df.Profit.mean())
n_df.head(3)

0     590.0
1     590.0
2    1366.0
Name: Profit, dtype: float64

In [83]:
df.sort_values(by=["Day"],ascending=True).head(5)

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
1858,5/1/2014,1,May,2014,53,Adults (35-64),M,United States,California,Accessories,Bottles and Cages,Water Bottle - 30 oz.,13,2.0,5.0,38.0,26.0,64.0
5213,10/1/2015,1,October,2015,25,Young Adults (25-34),M,Germany,Nordrhein-Westfalen,Accessories,Bottles and Cages,Road Bottle Cage,12,3.0,9.0,58.0,36.0,94.0
4978,4/1/2014,1,April,2014,36,Adults (35-64),F,United States,California,Accessories,Bottles and Cages,Water Bottle - 30 oz.,14,2.0,5.0,41.0,28.0,69.0
4979,4/1/2014,1,April,2014,36,Adults (35-64),F,United States,California,Accessories,Bottles and Cages,Water Bottle - 30 oz.,27,2.0,5.0,78.0,54.0,132.0
3132,3/1/2016,1,March,2016,42,Adults (35-64),F,Germany,Nordrhein-Westfalen,Accessories,Bottles and Cages,Water Bottle - 30 oz.,31,2.0,5.0,73.0,62.0,135.0

In [84]:
df[df.duplicated()]

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
1021,12/19/2013,19,December,2013,22,Youth (<25),M,Australia,New South Wales,Accessories,Bike Stands,All-Purpose Bike Stand,9,59.0,159.0,714.0,531.0,1245.0
1091,9/30/2015,30,September,2015,42,Adults (35-64),F,Australia,Victoria,Accessories,Bottles and Cages,Mountain Bottle Cage,5,4.0,10.0,20.0,20.0,40.0
1093,10/24/2013,24,October,2013,42,Adults (35-64),F,Australia,Victoria,Accessories,Bottles and Cages,Mountain Bottle Cage,2,4.0,10.0,8.0,8.0,16.0
1095,10/24/2015,24,October,2015,42,Adults (35-64),F,Australia,Victoria,Accessories,Bottles and Cages,Mountain Bottle Cage,1,4.0,10.0,4.0,4.0,8.0
1193,1/15/2016,15,January,2016,42,Adults (35-64),M,France,Seine Saint Denis,Accessories,Bottles and Cages,Water Bottle - 30 oz.,14,2.0,5.0,29.0,28.0,57.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7223,9/22/2015,22,September,2015,60,Adults (35-64),M,Canada,British Columbia,Accessories,Bottles and Cages,Water Bottle - 30 oz.,12,2.0,5.0,35.0,24.0,59.0
7401,4/21/2014,21,April,2014,33,Young Adults (25-34),M,United States,Washington,Accessories,Bottles and Cages,Water Bottle - 30 oz.,18,2.0,5.0,34.0,36.0,70.0
7461,11/15/2015,15,November,2015,28,Young Adults (25-34),M,Germany,Hamburg,Accessories,Bottles and Cages,Road Bottle Cage,22,3.0,9.0,118.0,66.0,184.0
7593,3/26/2014,26,March,2014,38,Adults (35-64),M,Germany,Bayern,Accessories,Bottles and Cages,Road Bottle Cage,12,3.0,9.0,71.0,36.0,107.0
7595,3/26/2016,26,March,2016,38,Adults (35-64),M,Germany,Bayern,Accessories,Bottles and Cages,Road Bottle Cage,12,3.0,9.0,71.0,36.0,107.0

In [85]:
df.drop_duplicates()

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,11/26/2013,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
1,11/26/2015,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
2,3/23/2014,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45.0,120.0,1366.0,1035.0,2401.0
3,3/23/2016,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45.0,120.0,1188.0,900.0,2088.0
4,5/15/2014,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45.0,120.0,238.0,180.0,418.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7644,6/14/2014,14,June,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,15,2.0,5.0,42.0,30.0,72.0
7645,6/14/2014,14,June,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,10,2.0,5.0,28.0,20.0,48.0
7646,6/14/2016,14,June,2016,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,17,2.0,5.0,48.0,34.0,82.0
7647,6/14/2016,14,June,2016,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,11,2.0,5.0,31.0,22.0,53.0
7648,6/17/2014,17,June,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,6,2.0,5.0,NaN,NaN,NaN

In [86]:
new_df=df.fillna(0)
new_df.head()

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,11/26/2013,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
1,11/26/2015,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
2,3/23/2014,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45.0,120.0,1366.0,1035.0,2401.0
3,3/23/2016,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45.0,120.0,1188.0,900.0,2088.0
4,5/15/2014,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45.0,120.0,238.0,180.0,418.0

In [87]:
new_df=df.fillna(method='bfill')
new_df.head()

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,11/26/2013,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
1,11/26/2015,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
2,3/23/2014,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45.0,120.0,1366.0,1035.0,2401.0
3,3/23/2016,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45.0,120.0,1188.0,900.0,2088.0
4,5/15/2014,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45.0,120.0,238.0,180.0,418.0

In [88]:
new_df=df.fillna(method='ffill')
new_df.head()

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,11/26/2013,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
1,11/26/2015,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
2,3/23/2014,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45.0,120.0,1366.0,1035.0,2401.0
3,3/23/2016,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45.0,120.0,1188.0,900.0,2088.0
4,5/15/2014,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45.0,120.0,238.0,180.0,418.0

In [89]:
new_df=df.dropna()
new_df.head()

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,11/26/2013,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
1,11/26/2015,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
2,3/23/2014,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45.0,120.0,1366.0,1035.0,2401.0
3,3/23/2016,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45.0,120.0,1188.0,900.0,2088.0
4,5/15/2014,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45.0,120.0,238.0,180.0,418.0

In [94]:
df.groupby("State").mean()

C:\Users\DW\AppData\Local\Temp\ipykernel_20888\1295520631.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby("State").mean()

,Day,Year,Customer_Age,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
State,,,,,,,,,
Alberta,23.250000,2014.750000,50.500000,7.250000,24.500000,65.000000,233.250000,141.750000,375.000000
Bayern,14.225806,2014.645161,37.677419,15.153226,5.774194,15.274194,105.951613,66.532258,172.483871
Brandenburg,8.333333,2014.333333,40.000000,20.250000,3.333333,9.333333,119.666667,67.500000,187.166667
British Columbia,15.419152,2014.590267,36.927786,14.160126,7.648352,20.017296,115.029898,72.591837,187.930141
California,14.986627,2014.603269,35.389302,14.426449,10.502229,27.842496,145.294948,92.209510,237.504458
Charente-Maritime,17.500000,2014.666667,28.000000,12.000000,2.333333,6.333333,54.083333,30.583333,84.666667
England,15.879776,2014.607642,36.796831,13.808947,7.655172,20.353215,98.970149,64.311567,163.281716
Essonne,15.980392,2014.549020,38.901961,15.411765,4.470588,11.666667,71.833333,48.745098,120.578431
Florida,1.000000,2015.000000,29.000000,16.000000,4.000000,10.000000,88.250000,64.000000,152.250000
Garonne (Haute),9.375000,2014.875000,35.625000,11.562500,2.500000,6.250000,38.500000,28.500000,67.000000
Hamburg,14.971831,2014.605634,34.591549,12.457746,6.112676,16.239437,80.915493,54.640845,135.556338
Hauts de Seine,12.125000,2014.500000,39.156250,15.203125,6.781250,17.968750,92.421875,63.531250,155.953125
Hessen,16.246575,2014.671233,37.808219,13.589041,7.753425,20.904110,133.650685,88.719178,222.369863
Illinois,23.000000,2014.000000,23.000000,12.500000,4.000000,10.000000,65.250000,50.000000,115.250000
Kentucky,4.000000,2014.000000,40.000000,1.000000,45.000000,120.000000,63.000000,45.000000,108.000000
Loir et Cher,21.200000,2014.600000,26.800000,16.800000,10.600000,28.000000,112.500000,85.200000,197.700000
Loiret,13.476190,2014.523810,29.428571,14.928571,9.857143,26.523810,124.095238,89.261905,213.357143
Moselle,13.454545,2014.454545,37.545455,14.136364,11.454545,30.363636,215.454545,162.681818,378.136364
New South Wales,15.625532,2014.655319,35.757447,13.763830,12.629787,33.748936,129.723404,98.748936,228.472340
New York,19.000000,2015.000000,49.000000,7.500000,2.000000,5.000000,17.750000,15.000000,32.750000
Nord,17.361702,2014.510638,41.106383,14.606383,13.085106,34.680851,146.351064,114.308511,260.659574
Nordrhein-Westfalen,14.666667,2014.548387,35.064516,15.021505,9.903226,26.526882,126.080645,95.510753,221.591398
Oregon,14.932468,2014.524675,36.241558,13.361039,8.594805,22.348958,97.992188,79.553247,178.348052
Pas de Calais,20.000000,2014.500000,35.000000,14.750000,2.000000,5.000000,33.375000,29.500000,62.875000
Queensland,14.471014,2014.579710,34.173913,13.159420,13.652174,36.934783,126.322464,98.021739,224.344203
Saarland,14.132530,2014.409639,34.831325,13.963855,11.036145,29.228916,102.475904,89.602410,192.078313
Seine (Paris),15.205479,2014.561644,39.534247,13.863014,8.301370,21.863014,75.815068,67.239726,143.054795
Seine Saint Denis,16.882353,2014.541176,36.682353,14.005882,6.364706,16.847059,74.558824,64.629412,139.188235
Seine et Marne,14.833333,2014.833333,33.055556,15.722222,5.333333,14.222222,57.472222,48.805556,106.277778
Somme,18.000000,2015.000000,31.000000,11.875000,3.000000,9.000000,52.000000,35.625000,87.625000
South Australia,15.159091,2014.568182,36.227273,14.068182,10.318182,27.613636,116.988636,97.625000,214.613636
South Carolina,16.000000,2015.000000,29.000000,14.500000,4.000000,10.000000,60.750000,58.000000,118.750000
Tasmania,16.157895,2014.473684,32.315789,18.105263,5.631579,14.842105,87.315789,78.315789,165.631579
Texas,12.000000,2014.666667,46.000000,11.833333,2.000000,5.000000,24.166667,23.666667,47.833333
Val d'Oise,13.222222,2014.222222,34.666667,14.611111,9.222222,25.000000,74.444444,63.444444,137.888889
Val de Marne,17.100000,2014.400000,37.000000,14.650000,8.300000,22.200000,113.600000,101.650000,215.250000
Victoria,16.484076,2014.662420,35.343949,13.837580,8.896774,24.789809,84.729299,79.261146,163.990446
Washington,15.881402,2014.560647,35.827493,13.885445,10.185984,26.964960,83.129380,80.113208,163.242588
Yveline,16.034483,2014.689655,31.655172,13.706897,9.275862,24.724138,69.810345,68.500000,138.310345

In [92]:
df.groupby('State').Cost.mean()

State
Alberta                141.750000
Bayern                  66.532258
Brandenburg             67.500000
British Columbia        72.591837
California              92.209510
Charente-Maritime       30.583333
England                 64.311567
Essonne                 48.745098
Florida                 64.000000
Garonne (Haute)         28.500000
Hamburg                 54.640845
Hauts de Seine          63.531250
Hessen                  88.719178
Illinois                50.000000
Kentucky                45.000000
Loir et Cher            85.200000
Loiret                  89.261905
Moselle                162.681818
New South Wales         98.748936
New York                15.000000
Nord                   114.308511
Nordrhein-Westfalen     95.510753
Oregon                  79.553247
Pas de Calais           29.500000
Queensland              98.021739
Saarland                89.602410
Seine (Paris)           67.239726
Seine Saint Denis       64.629412
Seine et Marne          48.805556
Somme                   35.625000
South Australia         97.625000
South Carolina          58.000000
Tasmania                78.315789
Texas                   23.666667
Val d'Oise              63.444444
Val de Marne           101.650000
Victoria                79.261146
Washington              80.113208
Yveline                 68.500000
Name: Cost, dtype: float64

In [95]:
df=pd.DataFrame(
    {
'name':[ 'Rowida', 'Shimaa','Shimaa','Rowida'],
'year':[2022,2022,2023,2024],
        'weight':[35,33,34,50]

    
    })
df

     name  year  weight
0  Rowida  2022      35
1  Shimaa  2022      33
2  Shimaa  2023      34
3  Rowida  2024      50

In [96]:
df.pivot_table(index='name',columns='year',values='weight',aggfunc='mean')

year    2022  2023  2024
name
Rowida  35.0   NaN  50.0
Shimaa  33.0  34.0   NaN