In [140]:
import pandas as pd
import numpy as np

In [141]:
df=pd.read_csv("Salest1.csv")
df

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,11/26/2013,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
1,11/26/2015,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
2,3/23/2014,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45.0,120.0,1366.0,1035.0,2401.0
3,3/23/2016,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45.0,120.0,1188.0,900.0,2088.0
4,5/15/2014,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45.0,120.0,238.0,180.0,418.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7644,6/14/2014,14,June,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,15,2.0,5.0,42.0,30.0,72.0
7645,6/14/2014,14,June,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,10,2.0,5.0,28.0,20.0,48.0
7646,6/14/2016,14,June,2016,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,17,2.0,5.0,48.0,34.0,82.0
7647,6/14/2016,14,June,2016,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,11,2.0,5.0,31.0,22.0,53.0
7648,6/17/2014,17,June,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,6,2.0,5.0,NaN,NaN,NaN

In [133]:
df.drop(['Unit_Cost','Day'], axis=1 ,inplace=True)
df.head()

,Date,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Price,Profit,Cost,Revenue
0,11/26/2013,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,120.0,590.0,360.0,950.0
1,11/26/2015,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,120.0,590.0,360.0,950.0
2,3/23/2014,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,120.0,1366.0,1035.0,2401.0
3,3/23/2016,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,120.0,1188.0,900.0,2088.0
4,5/15/2014,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,120.0,238.0,180.0,418.0

In [136]:
df.index

Float64Index([ 360.0,  360.0, 1035.0,  900.0,  180.0,  225.0,  180.0,   90.0,
               990.0,  945.0,
              ...
                28.0,   12.0,   36.0,   16.0,   30.0,   30.0,   20.0,   34.0,
                22.0,    nan],
             dtype='float64', name='Cost', length=7649)

In [43]:
df.head(5)

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,11/26/2013,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
1,11/26/2015,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
2,3/23/2014,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45.0,120.0,1366.0,1035.0,2401.0
3,3/23/2016,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45.0,120.0,1188.0,900.0,2088.0
4,5/15/2014,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45.0,120.0,238.0,180.0,418.0

Series and Dataframe

In [44]:
Day={0:26,1:26,2:23,3:23}
Customer_Age={0:19,1:19,2:49,3:49}
Year={0:2013,1:2015,2:2014,3:2016 }
Date={0:11_26_2013,1:11_26_2015,2:3_23_2014,3:3_23_2016}
Order_Quantity={0:8,1:8,2:23,3:20}
Unit_Cost={0:45,1:45,2:45,3:45}
Unit_Price={0:120,1:120,2:120,3:120}
Profit={0:590,1:590,2:1366,3:1188}
Cost={0:360,1:360,2:1035,3:900}
Revenue={0:950,1:950,2:2401,3:2088}
Day

{0: 26, 1: 26, 2: 23, 3: 23}

In [45]:
Customer_Age

{0: 19, 1: 19, 2: 49, 3: 49}

In [46]:
Year

{0: 2013, 1: 2015, 2: 2014, 3: 2016}

In [47]:
Date

{0: 11262013, 1: 11262015, 2: 3232014, 3: 3232016}

In [48]:
Order_Quantity

{0: 8, 1: 8, 2: 23, 3: 20}

In [49]:
Unit_Cost

{0: 45, 1: 45, 2: 45, 3: 45}

In [50]:
Unit_Price

{0: 120, 1: 120, 2: 120, 3: 120}

In [51]:
Profit

{0: 590, 1: 590, 2: 1366, 3: 1188}

In [52]:
Cost

{0: 360, 1: 360, 2: 1035, 3: 900}

In [53]:
Revenue

{0: 950, 1: 950, 2: 2401, 3: 2088}

In [29]:
Day=pd.Series(Day)
Day

0    26
1    26
2    23
3    23
dtype: int64

In [30]:
Customer_Age=pd.Series(Customer_Age)
Customer_Age

0    19
1    19
2    49
3    49
dtype: int64

In [54]:
Year=pd.Series(Year)
Year

0    2013
1    2015
2    2014
3    2016
dtype: int64

In [57]:
Date=pd.Series(Date)
Date

0    11262013
1    11262015
2     3232014
3     3232016
dtype: int64

In [58]:
Order_Quantity=pd.Series(Order_Quantity)
Order_Quantity

0     8
1     8
2    23
3    20
dtype: int64

In [59]:
Unit_Cost=pd.Series(Unit_Cost)
Unit_Cost

0    45
1    45
2    45
3    45
dtype: int64

In [60]:
Unit_Price=pd.Series(Unit_Price)
Unit_Price

0    120
1    120
2    120
3    120
dtype: int64

In [61]:
Profit=pd.Series(Profit)
Profit

0     590
1     590
2    1366
3    1188
dtype: int64

In [62]:
Cost=pd.Series(Cost)
Cost

0     360
1     360
2    1035
3     900
dtype: int64

In [63]:
Revenue=pd.Series(Revenue)
Revenue

0     950
1     950
2    2401
3    2088
dtype: int64

In [64]:
df=pd.DataFrame({"Day":Day,"Customer_Age":Customer_Age,"Year":Year,"Date":Date,"Order_Quantity":Order_Quantity,"Unit_Cost":Unit_Cost,"Unit_Price":Unit_Price,"Profit":Profit,
                "Cost":Cost,"Revenue":Revenue})
df

,Day,Customer_Age,Year,Date,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,26,19,11262013,11262013,8,45,120,590,360,950
1,26,19,11262015,11262015,8,45,120,590,360,950
2,23,49,3232014,3232014,23,45,120,1366,1035,2401
3,23,49,3232016,3232016,20,45,120,1188,900,2088

In [85]:
n=np.arange(1,5)
n
s=pd.Series(n,index=["a","b","c","d"])
s

a    1
b    2
c    3
d    4
dtype: int32

In [84]:
df.dtypes

Date                 object
Day                   int64
Month                object
Year                  int64
Customer_Age          int64
Age_Group            object
Customer_Gender      object
Country              object
State                object
Product_Category     object
Sub_Category         object
Product              object
Order_Quantity        int64
Unit_Cost           float64
Unit_Price          float64
Profit              float64
Cost                float64
Revenue             float64
dtype: object

In [83]:
df.columns

Index(['Date', 'Day', 'Month', 'Year', 'Customer_Age', 'Age_Group',
       'Customer_Gender', 'Country', 'State', 'Product_Category',
       'Sub_Category', 'Product', 'Order_Quantity', 'Unit_Cost', 'Unit_Price',
       'Profit', 'Cost', 'Revenue'],
      dtype='object')

In [82]:
for i in df.columns:
    print(i)

Date
Day
Month
Year
Customer_Age
Age_Group
Customer_Gender
Country
State
Product_Category
Sub_Category
Product
Order_Quantity
Unit_Cost
Unit_Price
Profit
Cost
Revenue

In [81]:
df.info

<bound method DataFrame.info of             Date  Day     Month  Year  Customer_Age             Age_Group  \
0     11/26/2013   26  November  2013            19           Youth (<25)
1     11/26/2015   26  November  2015            19           Youth (<25)
2      3/23/2014   23     March  2014            49        Adults (35-64)
3      3/23/2016   23     March  2016            49        Adults (35-64)
4      5/15/2014   15       May  2014            47        Adults (35-64)
...          ...  ...       ...   ...           ...                   ...
7644   6/14/2014   14      June  2014            29  Young Adults (25-34)
7645   6/14/2014   14      June  2014            29  Young Adults (25-34)
7646   6/14/2016   14      June  2016            29  Young Adults (25-34)
7647   6/14/2016   14      June  2016            29  Young Adults (25-34)
7648   6/17/2014   17      June  2014            29  Young Adults (25-34)

     Customer_Gender         Country             State Product_Category  \
0                  M          Canada  British Columbia      Accessories
1                  M          Canada  British Columbia      Accessories
2                  M       Australia   New South Wales      Accessories
3                  M       Australia   New South Wales      Accessories
4                  F       Australia   New South Wales      Accessories
...              ...             ...               ...              ...
7644               F  United Kingdom           England      Accessories
7645               F  United Kingdom           England      Accessories
7646               F  United Kingdom           England      Accessories
7647               F  United Kingdom           England      Accessories
7648               F  United Kingdom           England      Accessories

           Sub_Category                Product  Order_Quantity  Unit_Cost  \
0            Bike Racks    Hitch Rack - 4-Bike               8       45.0
1            Bike Racks    Hitch Rack - 4-Bike               8       45.0
2            Bike Racks    Hitch Rack - 4-Bike              23       45.0
3            Bike Racks    Hitch Rack - 4-Bike              20       45.0
4            Bike Racks    Hitch Rack - 4-Bike               4       45.0
...                 ...                    ...             ...        ...
7644  Bottles and Cages  Water Bottle - 30 oz.              15        2.0
7645  Bottles and Cages  Water Bottle - 30 oz.              10        2.0
7646  Bottles and Cages  Water Bottle - 30 oz.              17        2.0
7647  Bottles and Cages  Water Bottle - 30 oz.              11        2.0
7648  Bottles and Cages  Water Bottle - 30 oz.               6        2.0

      Unit_Price  Profit    Cost  Revenue
0          120.0   590.0   360.0    950.0
1          120.0   590.0   360.0    950.0
2          120.0  1366.0  1035.0   2401.0
3          120.0  1188.0   900.0   2088.0
4          120.0   238.0   180.0    418.0
...          ...     ...     ...      ...
7644         5.0    42.0    30.0     72.0
7645         5.0    28.0    20.0     48.0
7646         5.0    48.0    34.0     82.0
7647         5.0    31.0    22.0     53.0
7648         5.0     NaN     NaN      NaN

[7649 rows x 18 columns]>

In [80]:
df.describe()

,Day,Year,Customer_Age,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
count,7649.000000,7649.000000,7649.000000,7649.000000,7645.000000,7642.000000,7642.000000,7648.000000,7648.000000
mean,15.402144,2014.589097,36.135835,14.033468,9.168084,24.303455,110.904344,79.873431,190.986140
std,8.877280,1.114492,11.004788,8.829802,16.874770,45.342096,206.912793,141.821761,347.698752
min,1.000000,2013.000000,17.000000,1.000000,2.000000,5.000000,2.000000,2.000000,4.000000
25%,8.000000,2014.000000,28.000000,6.000000,2.000000,5.000000,26.000000,20.000000,47.000000
50%,15.000000,2014.000000,35.000000,13.000000,2.000000,5.000000,53.000000,42.000000,95.000000
75%,23.000000,2016.000000,43.000000,22.000000,4.000000,10.000000,88.000000,60.000000,149.000000
max,31.000000,2016.000000,87.000000,32.000000,59.000000,159.000000,2214.000000,1350.000000,3564.000000

In [79]:
df.Order_Quantity.value_counts()

1     420
5     342
3     326
6     319
8     309
7     306
4     303
2     299
9     286
10    282
20    250
18    247
13    241
14    240
11    236
15    232
27    223
16    222
24    221
12    220
17    219
23    218
22    217
19    216
26    214
28    212
25    209
21    209
29    178
30    171
31     35
32     27
Name: Order_Quantity, dtype: int64

In [86]:
df.Order_Quantity.unique()

array([ 8, 23, 20,  4,  5,  2, 22, 21,  7,  1,  6,  9,  3, 24, 25, 10, 11,
       12, 14, 28, 27, 15, 13, 17, 16, 30, 29, 26, 19, 18, 31, 32],
      dtype=int64)

In [88]:
df.Unit_Cost.dtype

dtype('float64')

In [89]:
df.Date

0       11/26/2013
1       11/26/2015
2        3/23/2014
3        3/23/2016
4        5/15/2014
           ...
7644     6/14/2014
7645     6/14/2014
7646     6/14/2016
7647     6/14/2016
7648     6/17/2014
Name: Date, Length: 7649, dtype: object

In [92]:
df[['Unit_Cost','Date']].head()

   Unit_Cost        Date
0       45.0  11/26/2013
1       45.0  11/26/2015
2       45.0   3/23/2014
3       45.0   3/23/2016
4       45.0   5/15/2014

In [93]:
df.Cost.min()

2.0

In [94]:
df.Cost==df.Cost.max()

0       False
1       False
2       False
3       False
4       False
        ...
7644    False
7645    False
7646    False
7647    False
7648    False
Name: Cost, Length: 7649, dtype: bool

In [95]:
df[df.Cost==df.Cost.max()]

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
90,2/12/2014,12,February,2014,46,Adults (35-64),M,United States,California,Accessories,Bike Racks,Hitch Rack - 4-Bike,30,45.0,120.0,2178.0,1350.0,3528.0
182,1/17/2014,17,January,2014,53,Adults (35-64),F,United States,California,Accessories,Bike Racks,Hitch Rack - 4-Bike,30,45.0,120.0,2178.0,1350.0,3528.0
192,12/14/2013,14,December,2013,59,Adults (35-64),F,United States,Washington,Accessories,Bike Racks,Hitch Rack - 4-Bike,30,45.0,120.0,1458.0,1350.0,2808.0
193,12/14/2015,14,December,2015,59,Adults (35-64),F,United States,Washington,Accessories,Bike Racks,Hitch Rack - 4-Bike,30,45.0,120.0,1458.0,1350.0,2808.0
245,1/7/2016,7,January,2016,31,Young Adults (25-34),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,30,45.0,120.0,2214.0,1350.0,3564.0

In [96]:
df[df.Cost==df.Cost.max()][['Unit_Cost','Date']]

     Unit_Cost        Date
90        45.0   2/12/2014
182       45.0   1/17/2014
192       45.0  12/14/2013
193       45.0  12/14/2015
245       45.0    1/7/2016

In [97]:
df.Product_Category.describe()

count            7649
unique              1
top       Accessories
freq             7649
Name: Product_Category, dtype: object

In [99]:
df1=df
df1

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,11/26/2013,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
1,11/26/2015,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,360.0,950.0
2,3/23/2014,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45.0,120.0,1366.0,1035.0,2401.0
3,3/23/2016,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45.0,120.0,1188.0,900.0,2088.0
4,5/15/2014,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45.0,120.0,238.0,180.0,418.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7644,6/14/2014,14,June,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,15,2.0,5.0,42.0,30.0,72.0
7645,6/14/2014,14,June,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,10,2.0,5.0,28.0,20.0,48.0
7646,6/14/2016,14,June,2016,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,17,2.0,5.0,48.0,34.0,82.0
7647,6/14/2016,14,June,2016,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,11,2.0,5.0,31.0,22.0,53.0
7648,6/17/2014,17,June,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,6,2.0,5.0,NaN,NaN,NaN

In [154]:
df1=df.copy()
df1

,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Revenue
Cost,,,,,,,,,,,,,,,,
360.0,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,950.0
360.0,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45.0,120.0,590.0,950.0
1035.0,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45.0,120.0,1366.0,2401.0
900.0,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45.0,120.0,1188.0,2088.0
180.0,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45.0,120.0,238.0,418.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30.0,14,June,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,15,2.0,5.0,42.0,72.0
20.0,14,June,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,10,2.0,5.0,28.0,48.0
34.0,14,June,2016,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,17,2.0,5.0,48.0,82.0
22.0,14,June,2016,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,11,2.0,5.0,31.0,53.0
NaN,17,June,2014,29,Young Adults (25-34),F,United Kingdom,England,Accessories,Bottles and Cages,Water Bottle - 30 oz.,6,2.0,5.0,NaN,NaN

In [155]:
df1.values

array([[26, 'November', 2013, ..., 120.0, 590.0, 950.0],
       [26, 'November', 2015, ..., 120.0, 590.0, 950.0],
       [23, 'March', 2014, ..., 120.0, 1366.0, 2401.0],
       ...,
       [14, 'June', 2016, ..., 5.0, 48.0, 82.0],
       [14, 'June', 2016, ..., 5.0, 31.0, 53.0],
       [17, 'June', 2014, ..., 5.0, nan, nan]], dtype=object)