In [1]:
import pandas as pd

In [17]:
df=pd.read_csv("Ecommerce Purchases.txt.txt")
df

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3807,"48419 James Villages\nCharlesside, MN 05281",16 Od,PM,Mozilla/5.0 (iPod; U; CPU iPhone OS 3_0 like M...,Gray Group,3158950215096082,02/17,42,American Express,conniemyers@dixon-hoover.biz,Plant breeder/geneticist,185.183.203.158,es,70.32
3808,"41420 Morgan Square\nNew Sylviaton, NH 91906",04 lg,AM,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_3 like M...,Sanchez-Pugh,30144466817368,02/24,660,Maestro,bradleywilliam@pineda-buchanan.com,Environmental health practitioner,20.125.230.98,pt,8.30
3809,"308 Dixon Fords Suite 923\nNicoleton, MH 45145",52 YN,AM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_8)...,"Graham, Walker and Frazier",869929666344262,04/24,262,JCB 16 digit,laurengill@hotmail.com,Hotel manager,206.199.193.146,fr,3.73
3810,"7016 Richard Center Apt. 216\nNew Paulburgh, C...",53 WU,AM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_8_4; r...,"Kim, Harris and Lee",3528700667851234,11/18,435,American Express,balljessica@yahoo.com,"Engineer, communications",33.68.160.144,zh,49.73
3811,"625 Mclaughlin Inlet Apt. 375\nSouth Ruben, CO...",94 he,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows CE;...,Banks Group,869974335345498,01/22,457,Voyager,simmonsmelanie@gmail.com,Multimedia specialist,88.14.181.,NaN,NaN

### 1.Display Top 10 Rows of The Dataset

In [21]:
df.head(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
5,"7502 Powell Mission Apt. 768\nTravisland, VA 3...",21 XT,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...,Silva-Anderson,30246185196287,07/25,7169,Discover,ynguyen@gmail.com,Fish farm manager,55.96.152.147,ru,25.15
6,"93971 Conway Causeway\nAndersonburgh, AZ 75107",96 Xt,AM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Gibson and Sons,6011398782655569,07/24,714,VISA 16 digit,olivia04@yahoo.com,Dancer,127.252.144.18,de,88.56
7,"260 Rachel Plains Suite 366\nCastroberg, WV 24...",96 pG,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5350...,Marshall-Collins,561252141909,06/25,256,VISA 13 digit,phillip48@parks.info,Event organiser,224.247.97.150,pt,44.25
8,"2129 Dylan Burg\nNew Michelle, ME 28650",45 JN,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Galloway and Sons,180041795790001,04/24,899,JCB 16 digit,kdavis@rasmussen.com,Financial manager,146.234.201.229,ru,59.54
9,"3795 Dawson Extensions\nLake Tinafort, ID 88739",15 Ug,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,"Rivera, Buchanan and Ramirez",4396283918371,01/17,931,American Express,qcoleman@hunt-huerta.com,Forensic scientist,236.198.199.8,zh,95.63

### 2. Check Last 10 Rows of The Dataset

In [41]:
df.tail(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
3802,"0843 Bobby Port\nGordonbury, VT 23015-8557",57 sr,AM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_5_4...,Cruz PLC,6011081720218290,08/19,475,JCB 16 digit,tiffanylong@alvarez-frey.com,Sales executive,238.205.226.100,it,1.30
3803,"92679 Brown Parks\nEast Jason, IA 85954",53 lx,AM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_8_4; r...,Ward Inc,347812781765342,11/23,724,VISA 16 digit,vickistafford@hanson.net,Fisheries officer,191.111.91.133,ru,1.20
3804,"76678 Melissa Track\nSnowville, MP 02252",20 HG,AM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_5 ...,Meyer-Howe,675940649469,01/19,209,American Express,andrew41@coffey.org,Hydrologist,152.125.105.87,it,37.53
3805,USNS Anderson\nFPO AP 85662-4006,65 vG,PM,Mozilla/5.0 (Windows; U; Windows NT 5.0) Apple...,York-Baker,630486483286,03/20,992,JCB 16 digit,xryan@coffey-gordon.com,"Engineer, maintenance (IT)",188.203.215.48,es,76.10
3806,"6598 Chad Extensions\nNorristown, TX 53321",49 GN,AM,Mozilla/5.0 (Windows; U; Windows NT 5.01) Appl...,Ho LLC,3088701630877605,10/17,865,Voyager,nspence@davis-cruz.com,Psychiatric nurse,126.220.202.8,es,29.56
3807,"48419 James Villages\nCharlesside, MN 05281",16 Od,PM,Mozilla/5.0 (iPod; U; CPU iPhone OS 3_0 like M...,Gray Group,3158950215096082,02/17,42,American Express,conniemyers@dixon-hoover.biz,Plant breeder/geneticist,185.183.203.158,es,70.32
3808,"41420 Morgan Square\nNew Sylviaton, NH 91906",04 lg,AM,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_3 like M...,Sanchez-Pugh,30144466817368,02/24,660,Maestro,bradleywilliam@pineda-buchanan.com,Environmental health practitioner,20.125.230.98,pt,8.30
3809,"308 Dixon Fords Suite 923\nNicoleton, MH 45145",52 YN,AM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_8)...,"Graham, Walker and Frazier",869929666344262,04/24,262,JCB 16 digit,laurengill@hotmail.com,Hotel manager,206.199.193.146,fr,3.73
3810,"7016 Richard Center Apt. 216\nNew Paulburgh, C...",53 WU,AM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_8_4; r...,"Kim, Harris and Lee",3528700667851234,11/18,435,American Express,balljessica@yahoo.com,"Engineer, communications",33.68.160.144,zh,49.73
3811,"625 Mclaughlin Inlet Apt. 375\nSouth Ruben, CO...",94 he,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows CE;...,Banks Group,869974335345498,01/22,457,Voyager,simmonsmelanie@gmail.com,Multimedia specialist,88.14.181.,NaN,NaN

### 3. Check Datatype of Each Column

In [43]:

df.dtypes

Address              object
Lot                  object
AM or PM             object
Browser Info         object
Company              object
Credit Card           int64
CC Exp Date          object
CC Security Code      int64
CC Provider          object
Email                object
Job                  object
IP Address           object
Language             object
Purchase Price      float64
dtype: object

In [44]:
df.info

<bound method DataFrame.info of                                                 Address    Lot AM or PM  \
0     16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM
1     9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM
2                      Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM
3                 7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM
4     23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM
...                                                 ...    ...      ...
3807        48419 James Villages\nCharlesside, MN 05281  16 Od       PM
3808       41420 Morgan Square\nNew Sylviaton, NH 91906  04 lg       AM
3809     308 Dixon Fords Suite 923\nNicoleton, MH 45145  52 YN       AM
3810  7016 Richard Center Apt. 216\nNew Paulburgh, C...  53 WU       AM
3811  625 Mclaughlin Inlet Apt. 375\nSouth Ruben, CO...  94 he       PM

                                           Browser Info  \
0     Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...
1     Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...
2     Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...
3     Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...
4     Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...
...                                                 ...
3807  Mozilla/5.0 (iPod; U; CPU iPhone OS 3_0 like M...
3808  Mozilla/5.0 (iPod; U; CPU iPhone OS 4_3 like M...
3809  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_8)...
3810  Mozilla/5.0 (Macintosh; PPC Mac OS X 10_8_4; r...
3811  Mozilla/5.0 (compatible; MSIE 9.0; Windows CE;...

                              Company       Credit Card CC Exp Date  \
0                     Martinez-Herman  6011929061123406       02/20
1     Fletcher, Richards and Whitaker  3337758169645356       11/18
2          Simpson, Williams and Pham      675957666125       08/19
3     Williams, Marshall and Buchanan  6011578504430710       02/24
4           Brown, Watson and Andrews  6011456623207998       10/25
...                               ...               ...         ...
3807                       Gray Group  3158950215096082       02/17
3808                     Sanchez-Pugh    30144466817368       02/24
3809       Graham, Walker and Frazier   869929666344262       04/24
3810              Kim, Harris and Lee  3528700667851234       11/18
3811                      Banks Group   869974335345498       01/22

      CC Security Code                  CC Provider  \
0                  900                 JCB 16 digit
1                  561                   Mastercard
2                  699                 JCB 16 digit
3                  384                     Discover
4                  678  Diners Club / Carte Blanche
...                ...                          ...
3807                42             American Express
3808               660                      Maestro
3809               262                 JCB 16 digit
3810               435             American Express
3811               457                      Voyager

                                   Email  \
0                      pdunlap@yahoo.com
1                     anthony41@reed.com
2         amymiller@morales-harrison.com
3            brent16@olson-robinson.info
4            christopherwright@gmail.com
...                                  ...
3807        conniemyers@dixon-hoover.biz
3808  bradleywilliam@pineda-buchanan.com
3809              laurengill@hotmail.com
3810               balljessica@yahoo.com
3811            simmonsmelanie@gmail.com

                                         Job       IP Address Language  \
0     Scientist, product/process development  149.146.147.205       el
1                          Drilling engineer     15.160.41.51       fr
2                   Customer service manager   132.207.160.22       de
3                          Drilling engineer     30.250.74.19       es
4                                Fine artist     24.140.33.94       es
...                                      ...              ...      ...
3807                Plant breeder/geneticist  185.183.203.158       es
3808       Environmental health practitioner    20.125.230.98       pt
3809                           Hotel manager  206.199.193.146       fr
3810                Engineer, communications    33.68.160.144       zh
3811                   Multimedia specialist       88.14.181.      NaN

      Purchase Price
0              98.14
1              70.73
2               0.95
3              78.04
4              77.82
...              ...
3807           70.32
3808            8.30
3809            3.73
3810           49.73
3811             NaN

[3812 rows x 14 columns]>

### 4.Check Null Values In The Dataset

In [45]:
df.isna().sum()

Address             0
Lot                 0
AM or PM            0
Browser Info        0
Company             0
Credit Card         0
CC Exp Date         0
CC Security Code    0
CC Provider         0
Email               0
Job                 0
IP Address          0
Language            1
Purchase Price      1
dtype: int64

### 6. How Many Rows And Columns Are There In Our Dataset?

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3812 entries, 0 to 3811
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           3812 non-null   object
 1   Lot               3812 non-null   object
 2   AM or PM          3812 non-null   object
 3   Browser Info      3812 non-null   object
 4   Company           3812 non-null   object
 5   Credit Card       3812 non-null   int64
 6   CC Exp Date       3812 non-null   object
 7   CC Security Code  3812 non-null   int64
 8   CC Provider       3812 non-null   object
 9   Email             3812 non-null   object
 10  Job               3812 non-null   object
 11  IP Address        3812 non-null   object
 12  Language          3811 non-null   object
 13  Purchase Price    3811 non-null   float64
dtypes: float64(1), int64(2), object(11)
memory usage: 417.1+ KB

In [48]:
len(df)

3812

### 7. Highest And Lowest Purchase Prices

In [49]:
df.head(2)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73

In [55]:
df["Purchase Price"].min()

0.0

In [59]:
df["Purchase Price"].max()

99.99

### 8. Average Purchase Price

In [57]:
df["Purchase Price"].mean()

50.30394647074259

### 9 .How many people have French 'fr' as their Language ?

In [77]:
df.Language=='fr'

0       False
1        True
2       False
3       False
4       False
        ...
3807    False
3808    False
3809     True
3810    False
3811    False
Name: Language, Length: 3812, dtype: bool

### 10. Job Title Contains Engineer

In [68]:
df[df.Job=="Engineer"]

Empty DataFrame
Columns: [Address, Lot, AM or PM, Browser Info, Company, Credit Card, CC Exp Date, CC Security Code, CC Provider, Email, Job, IP Address, Language, Purchase Price]
Index: []

### 11. How Many People Have Mastercard As Their Credit Card Provider And Made A Purchase Above 50?

In [76]:
df[(df["CC Provider"]=="Mastercard")&(df["Purchase Price"]>=50)]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
18,"461 Christopher Square\nWest Michaelchester, C...",17 SB,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.6.20) Gec...,"Beard, Abbott and Pena",6011350184276270,12/22,767,Mastercard,hannah63@yahoo.com,Photographer,73.250.176.201,el,70.15
31,USNS Alvarado\nFPO AA 27052-1231,26 Lh,PM,Opera/8.84.(X11; Linux i686; sl-SI) Presto/2.9...,Nicholson Group,4614997834548,03/22,909,Mastercard,ashley12@hotmail.com,Sales executive,94.176.142.201,en,94.14
35,"93392 Webb Gardens Apt. 220\nLaurabury, AR 999...",37 om,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Mora Ltd,6011049630969815,09/16,367,Mastercard,hgonzalez@mcdowell.com,"Lecturer, further education",216.23.95.40,zh,97.46
90,"431 Bowen Lights\nFergusonborough, MH 01362",31 tG,AM,Mozilla/5.0 (Windows NT 5.2; it-IT; rv:1.9.1.2...,Copeland-Lee,639032576097,06/18,868,Mastercard,nrogers@brown.com,"Teacher, English as a foreign language",153.188.13.203,es,78.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3693,"9422 Michael Loaf Apt. 258\nColinville, ID 207...",36 uV,AM,Mozilla/5.0 (compatible; MSIE 6.0; Windows NT ...,"Miles, Harrington and Hernandez",345114026248586,02/18,5450,Mastercard,julianmoore@knight.com,Haematologist,190.246.244.153,de,99.66
3741,Unit 6500 Box 8386\nDPO AP 56519-4129,10 oR,AM,Opera/8.43.(X11; Linux x86_64; it-IT) Presto/2...,Mclean-Campbell,869956895813346,12/19,36,Mastercard,owalker@jenkins.info,Fish farm manager,243.215.25.147,de,75.67
3770,"5145 Austin Shoals Suite 297\nLake William, NY...",01 vY,AM,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,Pope-Tucker,6011426234981778,09/20,875,Mastercard,richard38@padilla-sullivan.org,Sports development officer,222.107.138.227,zh,87.53
3776,"697 Mckee Row\nKatieville, DE 77945-1867",38 fB,AM,Opera/8.78.(X11; Linux i686; sl-SI) Presto/2.9...,"Lucas, Jackson and Jones",5270627782196622,04/23,937,Mastercard,amandahenderson@moore.com,Herbalist,164.137.228.199,el,67.71
3789,"559 Hahn Road Apt. 860\nAaronville, MP 30305",66 Ci,PM,Mozilla/5.0 (Windows 95; en-US; rv:1.9.2.20) G...,"Cardenas, Leblanc and Clark",5383052010583638,08/19,415,Mastercard,smithcrystal@smith-davis.biz,"Scientist, research (maths)",208.66.46.21,it,63.55

### 12. Find Email of The Person With The Following Credit Card Number: 4664825258997302

In [90]:
df[df["Credit Card"]==4664825258997302]

Empty DataFrame
Columns: [Address, Lot, AM or PM, Browser Info, Company, Credit Card, CC Exp Date, CC Security Code, CC Provider, Email, Job, IP Address, Language, Purchase Price]
Index: []

### 13. How Many People Purchase During The AM and How Many People Purchase During PM ?

### 14. How Many People have A Credit Card That Expires In 2020?

### 15. What Are The Top 5 Most Popular Email providers (e.g. gmail.com, yahoo.com, etc...)

### 16. How much Purchase Price During The AM and During PM ?