In [2]:
 import pandas as pd

In [3]:
 df = pd.read_csv("employees.csv.csv")
df

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [3]:
df.info

<bound method DataFrame.info of     First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male    8/6/1993        12:42 PM   97308    6.945
1       Thomas    Male   3/31/1996         6:53 AM   61933    4.170
2        Maria  Female   4/23/1993        11:17 AM  130590   11.858
3        Jerry    Male    3/4/2005         1:00 PM  138705    9.340
4        Larry    Male   1/24/1998         4:47 PM  101004    1.389
..         ...     ...         ...             ...     ...      ...
995      Henry     NaN  11/23/2014         6:09 AM  132483   16.655
996    Phillip    Male   1/31/1984         6:30 AM   42392   19.675
997    Russell    Male   5/20/2013        12:39 PM   96914    1.421
998      Larry    Male   4/20/2013         4:45 PM   60500   11.985
999     Albert    Male   5/15/2012         6:24 PM  129949   10.169

    Senior Management                  Team
0                True             Marketing
1                True                   NaN
2               False               Finance
3                True               Finance
4                True       Client Services
..                ...                   ...
995             False          Distribution
996             False               Finance
997             False               Product
998             False  Business Development
999              True                 Sales

[1000 rows x 8 columns]>

In [4]:
df.describe()

              Salary      Bonus %
count    1000.000000  1000.000000
mean    90662.181000    10.207555
std     32923.693342     5.528481
min     35013.000000     1.015000
25%     62613.000000     5.401750
50%     90428.000000     9.838500
75%    118740.250000    14.838000
max    149908.000000    19.944000

In [5]:
df.describe(include='O')

,First Name,Gender,Start Date,Last Login Time,Senior Management,Team
count,933,855,1000,1000,933,957
unique,200,2,972,720,2,10
top,Marilyn,Female,10/30/1994,1:35 PM,True,Client Services
freq,11,431,2,5,468,106

In [6]:
df.columns

Index(['First Name', 'Gender', 'Start Date', 'Last Login Time', 'Salary',
       'Bonus %', 'Senior Management', 'Team'],
      dtype='object')

In [7]:
df.index

RangeIndex(start=0, stop=1000, step=1)

In [8]:
df.values

array([['Douglas', 'Male', '8/6/1993', ..., 6.945, True, 'Marketing'],
       ['Thomas', 'Male', '3/31/1996', ..., 4.17, True, nan],
       ['Maria', 'Female', '4/23/1993', ..., 11.858, False, 'Finance'],
       ...,
       ['Russell', 'Male', '5/20/2013', ..., 1.421, False, 'Product'],
       ['Larry', 'Male', '4/20/2013', ..., 11.985, False,
        'Business Development'],
       ['Albert', 'Male', '5/15/2012', ..., 10.169, True, 'Sales']],
      dtype=object)

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [11]:
df.isna()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,True,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [12]:
df.isna().sum()

First Name            67
Gender               145
Start Date             0
Last Login Time        0
Salary                 0
Bonus %                0
Senior Management     67
Team                  43
dtype: int64

In [13]:
df.set_index('First Name', inplace = True)

In [14]:
df.head()

,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
First Name,,,,,,,
Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [15]:
new_df=df.Team.fillna(df.Salary.mean())
new_df

First Name
Douglas               Marketing
Thomas                90662.181
Maria                   Finance
Jerry                   Finance
Larry           Client Services
                   ...
Henry              Distribution
Phillip                 Finance
Russell                 Product
Larry      Business Development
Albert                    Sales
Name: Team, Length: 1000, dtype: object

In [16]:
df.loc['Thomas']

,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
First Name,,,,,,,
Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
Thomas,Male,6/4/1995,2:24 PM,62096,17.029,False,Marketing
Thomas,Male,4/6/2011,1:04 PM,103235,9.554,True,Human Resources
Thomas,NaN,8/31/1995,8:31 PM,41549,3.950,False,Sales
Thomas,Male,9/7/1991,9:51 AM,65251,11.211,False,Distribution
Thomas,Male,5/3/1990,9:29 AM,111371,15.081,True,Engineering
Thomas,Male,3/12/2016,3:10 PM,105681,19.572,False,Engineering

In [17]:
df.drop(['Gender'], axis = 1, inplace = True)
df.head()

,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
First Name,,,,,,
Douglas,8/6/1993,12:42 PM,97308,6.945,True,Marketing
Thomas,3/31/1996,6:53 AM,61933,4.170,True,NaN
Maria,4/23/1993,11:17 AM,130590,11.858,False,Finance
Jerry,3/4/2005,1:00 PM,138705,9.340,True,Finance
Larry,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [4]:
df.sort_values(by=["First Name"],ascending=True).head(10)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
101,Aaron,Male,2/17/2012,10:20 AM,61602,11.849,True,Marketing
327,Aaron,Male,1/29/1994,6:48 PM,58755,5.097,True,Marketing
440,Aaron,Male,7/22/1990,2:53 PM,52119,11.343,True,Client Services
937,Aaron,NaN,1/22/1986,7:39 PM,63126,18.424,False,Client Services
137,Adam,Male,5/21/2011,1:45 AM,95327,15.120,False,Distribution
141,Adam,Male,12/24/1990,8:57 PM,110194,14.727,True,Product
302,Adam,Male,7/5/2007,11:59 AM,71276,5.027,True,Human Resources
538,Adam,Male,10/8/2010,9:53 PM,45181,3.491,False,Human Resources
300,Alan,Male,6/26/1988,3:54 AM,111786,3.592,True,Engineering
53,Alan,NaN,3/3/2014,1:28 PM,40341,17.578,True,Finance