In [118]:
import pandas as pd
import numpy as np

In [119]:
df=pd.read_csv("Documents/employees.csv.csv")
df

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [117]:
df=pd.DataFrame({
     'Salary':[ 97308,61933,130590,138705,101004,132483,42392,96914,60500,129949],
 
    'Gender':['Male',' Male', 'Female', 'Male',' Male',' Male', 'Male', 'Male', 'Male',' Male'],


     'Team':['Marketing','NaN','Finance','Finance','Client Services','Distribution','Finance','Product','BusinessDevelopment','Sales']
})
df

   Salary  Gender                 Team
0   97308    Male            Marketing
1   61933    Male                  NaN
2  130590  Female              Finance
3  138705    Male              Finance
4  101004    Male      Client Services
5  132483    Male         Distribution
6   42392    Male              Finance
7   96914    Male              Product
8   60500    Male  BusinessDevelopment
9  129949    Male                Sales

In [120]:
df.sample

<bound method NDFrame.sample of     First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male    8/6/1993        12:42 PM   97308    6.945
1       Thomas    Male   3/31/1996         6:53 AM   61933    4.170
2        Maria  Female   4/23/1993        11:17 AM  130590   11.858
3        Jerry    Male    3/4/2005         1:00 PM  138705    9.340
4        Larry    Male   1/24/1998         4:47 PM  101004    1.389
..         ...     ...         ...             ...     ...      ...
995      Henry     NaN  11/23/2014         6:09 AM  132483   16.655
996    Phillip    Male   1/31/1984         6:30 AM   42392   19.675
997    Russell    Male   5/20/2013        12:39 PM   96914    1.421
998      Larry    Male   4/20/2013         4:45 PM   60500   11.985
999     Albert    Male   5/15/2012         6:24 PM  129949   10.169

    Senior Management                  Team
0                True             Marketing
1                True                   NaN
2               False               Finance
3                True               Finance
4                True       Client Services
..                ...                   ...
995             False          Distribution
996             False               Finance
997             False               Product
998             False  Business Development
999              True                 Sales

[1000 rows x 8 columns]>

In [121]:
df.sample(frac=0.10)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
90,Janice,NaN,8/21/1997,5:12 AM,91719,11.583,True,Legal
660,Mary,NaN,12/24/1986,7:02 PM,100341,6.662,False,Distribution
758,Carl,NaN,8/18/2007,8:01 AM,98295,7.617,True,Legal
195,Ronald,Male,4/30/2014,2:19 PM,121068,12.757,True,Product
529,Christopher,Male,4/23/2014,7:52 AM,82401,7.252,False,Client Services
...,...,...,...,...,...,...,...,...
442,Julie,Female,4/23/1998,5:52 AM,73437,2.518,True,Finance
178,Jane,Female,9/3/1997,2:01 AM,144474,17.648,False,Product
617,Kathy,Female,1/14/2001,5:11 AM,45682,1.451,True,Marketing
752,Henry,Male,2/23/2007,3:24 AM,49665,18.338,False,Business Development
687,NaN,Male,12/27/1996,7:07 AM,139959,8.992,NaN,Distribution

In [122]:
df.head(50)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
9,Frances,Female,8/8/2002,6:51 AM,139852,7.524,True,Business Development
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,NaN
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,6/5/2016,6:09 AM,59414,1.256,False,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,False,Human Resources
17,Shawn,Male,12/7/1986,7:45 PM,111737,6.414,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product
20,Lois,NaN,4/22/1995,7:18 PM,64714,4.934,True,Legal
21,Matthew,Male,9/5/1995,2:12 AM,100612,13.645,False,Marketing
22,Joshua,NaN,3/8/2012,1:58 AM,90816,18.816,True,Client Services
23,NaN,Male,6/14/2012,4:19 PM,125792,5.042,NaN,NaN
24,John,Male,7/1/1992,10:08 PM,97950,13.873,False,Client Services
25,NaN,Male,10/8/2012,1:12 AM,37076,18.576,NaN,Client Services
26,Craig,Male,2/27/2000,7:45 AM,37598,7.757,True,Marketing
27,Scott,NaN,7/11/1991,6:58 PM,122367,5.218,False,Legal
28,Terry,Male,11/27/1981,6:30 PM,124008,13.464,True,Client Services
29,Benjamin,Male,1/26/2005,10:06 PM,79529,7.008,True,Legal
30,Christina,Female,8/6/2002,1:19 PM,118780,9.096,True,Engineering
31,Joyce,NaN,2/20/2005,2:40 PM,88657,12.752,False,Product
32,NaN,Male,8/21/1998,2:27 PM,122340,6.417,NaN,NaN
33,Jean,Female,12/18/1993,9:07 AM,119082,16.180,False,Business Development
34,Jerry,Male,1/10/2004,12:56 PM,95734,19.096,False,Client Services
35,Theresa,Female,10/10/2006,1:12 AM,85182,16.675,False,Sales
36,Rachel,Female,2/16/2009,8:47 PM,142032,12.599,False,Business Development
37,Linda,Female,10/19/1981,8:49 PM,57427,9.557,True,Client Services
38,Stephanie,Female,9/13/1986,1:52 AM,36844,5.574,True,Business Development
39,NaN,Male,1/29/2016,2:33 AM,122173,7.797,NaN,Client Services
40,Michael,Male,10/10/2008,11:25 AM,99283,2.665,True,Distribution
41,Christine,NaN,6/28/2015,1:08 AM,66582,11.308,True,Business Development
42,Beverly,Female,9/9/1998,8:26 PM,121918,15.835,False,Legal
43,Marilyn,Female,12/7/1980,3:16 AM,73524,5.207,True,Marketing
44,Cynthia,Female,11/16/1988,6:54 PM,145146,7.482,True,Product
45,Roger,Male,4/17/1980,11:32 AM,88010,13.886,True,Sales
46,Bruce,Male,11/28/2009,10:47 PM,114796,6.796,False,Finance
47,Kathy,Female,6/22/2005,4:51 AM,66820,9.000,True,Client Services
48,Clarence,Male,3/26/1996,5:57 AM,93581,6.083,True,Business Development
49,Chris,NaN,1/24/1980,12:13 PM,113590,3.055,False,Sales

In [141]:
df.isna()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [147]:
ff=df.Gender.fillna(df.Gender.ffill(), inplace =True)
df.head(30)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,Finance
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
7,Angela,Female,7/20/2015,10:43 AM,45906,11.598,True,Finance
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
9,Frances,Female,8/8/2002,6:51 AM,139852,7.524,True,Business Development
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,Legal
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,6/5/2016,6:09 AM,59414,1.256,False,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,False,Human Resources
17,Shawn,Male,12/7/1986,7:45 PM,111737,6.414,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product
20,Lois,Female,4/22/1995,7:18 PM,64714,4.934,True,Legal
21,Matthew,Male,9/5/1995,2:12 AM,100612,13.645,False,Marketing
22,Joshua,Male,3/8/2012,1:58 AM,90816,18.816,True,Client Services
23,John,Male,6/14/2012,4:19 PM,125792,5.042,False,Client Services
24,John,Male,7/1/1992,10:08 PM,97950,13.873,False,Client Services
25,Craig,Male,10/8/2012,1:12 AM,37076,18.576,True,Client Services
26,Craig,Male,2/27/2000,7:45 AM,37598,7.757,True,Marketing
27,Scott,Male,7/11/1991,6:58 PM,122367,5.218,False,Legal
28,Terry,Male,11/27/1981,6:30 PM,124008,13.464,True,Client Services
29,Benjamin,Male,1/26/2005,10:06 PM,79529,7.008,True,Legal

In [143]:
df=df.fillna(method="bfill")
df.head(30)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,Finance
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
7,Angela,Female,7/20/2015,10:43 AM,45906,11.598,True,Finance
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
9,Frances,Female,8/8/2002,6:51 AM,139852,7.524,True,Business Development
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,Legal
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,6/5/2016,6:09 AM,59414,1.256,False,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,False,Human Resources
17,Shawn,Male,12/7/1986,7:45 PM,111737,6.414,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product
20,Lois,Female,4/22/1995,7:18 PM,64714,4.934,True,Legal
21,Matthew,Male,9/5/1995,2:12 AM,100612,13.645,False,Marketing
22,Joshua,Male,3/8/2012,1:58 AM,90816,18.816,True,Client Services
23,John,Male,6/14/2012,4:19 PM,125792,5.042,False,Client Services
24,John,Male,7/1/1992,10:08 PM,97950,13.873,False,Client Services
25,Craig,Male,10/8/2012,1:12 AM,37076,18.576,True,Client Services
26,Craig,Male,2/27/2000,7:45 AM,37598,7.757,True,Marketing
27,Scott,Male,7/11/1991,6:58 PM,122367,5.218,False,Legal
28,Terry,Male,11/27/1981,6:30 PM,124008,13.464,True,Client Services
29,Benjamin,Male,1/26/2005,10:06 PM,79529,7.008,True,Legal

In [146]:
ff=df.fillna(method="ffill")
df.head(30)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,Finance
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
7,Angela,Female,7/20/2015,10:43 AM,45906,11.598,True,Finance
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
9,Frances,Female,8/8/2002,6:51 AM,139852,7.524,True,Business Development
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,Legal
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,6/5/2016,6:09 AM,59414,1.256,False,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,False,Human Resources
17,Shawn,Male,12/7/1986,7:45 PM,111737,6.414,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product
20,Lois,Female,4/22/1995,7:18 PM,64714,4.934,True,Legal
21,Matthew,Male,9/5/1995,2:12 AM,100612,13.645,False,Marketing
22,Joshua,Male,3/8/2012,1:58 AM,90816,18.816,True,Client Services
23,John,Male,6/14/2012,4:19 PM,125792,5.042,False,Client Services
24,John,Male,7/1/1992,10:08 PM,97950,13.873,False,Client Services
25,Craig,Male,10/8/2012,1:12 AM,37076,18.576,True,Client Services
26,Craig,Male,2/27/2000,7:45 AM,37598,7.757,True,Marketing
27,Scott,Male,7/11/1991,6:58 PM,122367,5.218,False,Legal
28,Terry,Male,11/27/1981,6:30 PM,124008,13.464,True,Client Services
29,Benjamin,Male,1/26/2005,10:06 PM,79529,7.008,True,Legal

In [145]:
new_df=df.Salary.fillna(df.Salary.mean())
new_df.head()

0     97308
1     61933
2    130590
3    138705
4    101004
Name: Salary, dtype: int64

In [125]:
new_df=df.fillna(
    {
   'Gender': "missing"   
    }
)
new_df.head(30)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
9,Frances,Female,8/8/2002,6:51 AM,139852,7.524,True,Business Development
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,NaN
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,6/5/2016,6:09 AM,59414,1.256,False,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,False,Human Resources
17,Shawn,Male,12/7/1986,7:45 PM,111737,6.414,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product
20,Lois,missing,4/22/1995,7:18 PM,64714,4.934,True,Legal
21,Matthew,Male,9/5/1995,2:12 AM,100612,13.645,False,Marketing
22,Joshua,missing,3/8/2012,1:58 AM,90816,18.816,True,Client Services
23,NaN,Male,6/14/2012,4:19 PM,125792,5.042,NaN,NaN
24,John,Male,7/1/1992,10:08 PM,97950,13.873,False,Client Services
25,NaN,Male,10/8/2012,1:12 AM,37076,18.576,NaN,Client Services
26,Craig,Male,2/27/2000,7:45 AM,37598,7.757,True,Marketing
27,Scott,missing,7/11/1991,6:58 PM,122367,5.218,False,Legal
28,Terry,Male,11/27/1981,6:30 PM,124008,13.464,True,Client Services
29,Benjamin,Male,1/26/2005,10:06 PM,79529,7.008,True,Legal

In [126]:
df.dropna()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [127]:
fill=df.Salary.quantile(0.65)
fill

106443.4

In [128]:
new_df=df.Salary.fillna(fill, inplace=True)
df.head(10)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
9,Frances,Female,8/8/2002,6:51 AM,139852,7.524,True,Business Development