# **IMPORT LIBRARIES**

In [ ]:
import pandas as pd
from google.colab import files
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

# **UPLOAD DATA**

In [ ]:
uploaded = files.upload()
df = pd.read_csv('stroke_prediction_dataset.csv')
df.head()

Saving stroke_prediction_dataset.csv to stroke_prediction_dataset.csv

,Patient ID,Patient Name,Age,Gender,Hypertension,Heart Disease,Marital Status,Work Type,Residence Type,Average Glucose Level,...,Alcohol Intake,Physical Activity,Stroke History,Family History of Stroke,Dietary Habits,Stress Levels,Blood Pressure Levels,Cholesterol Levels,Symptoms,Diagnosis
0,18153,Mamooty Khurana,56,Male,0,1,Married,Self-employed,Rural,130.91,...,Social Drinker,Moderate,0,Yes,Vegan,3.48,140/108,"HDL: 68, LDL: 133","Difficulty Speaking, Headache",Stroke
1,62749,Kaira Subramaniam,80,Male,0,0,Single,Self-employed,Urban,183.73,...,Never,Low,0,No,Paleo,1.73,146/91,"HDL: 63, LDL: 70","Loss of Balance, Headache, Dizziness, Confusion",Stroke
2,32145,Dhanush Balan,26,Male,1,1,Married,Never Worked,Rural,189.00,...,Rarely,High,0,Yes,Paleo,7.31,154/97,"HDL: 59, LDL: 95","Seizures, Dizziness",Stroke
3,6154,Ivana Baral,73,Male,0,0,Married,Never Worked,Urban,185.29,...,Frequent Drinker,Moderate,0,No,Paleo,5.35,174/81,"HDL: 70, LDL: 137","Seizures, Blurred Vision, Severe Fatigue, Head...",No Stroke
4,48973,Darshit Jayaraman,51,Male,1,1,Divorced,Self-employed,Urban,177.34,...,Rarely,Low,0,Yes,Pescatarian,6.84,121/95,"HDL: 65, LDL: 68",Difficulty Speaking,Stroke

# **DATA OVERVIEW**

In [ ]:
# Check the shape of the dataset (rows, columns)
print("Dataset shape:", df.shape)

Dataset shape: (15000, 22)

In [ ]:
# Check info about columns and types
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Patient ID                15000 non-null  int64
 1   Patient Name              15000 non-null  object
 2   Age                       15000 non-null  int64
 3   Gender                    15000 non-null  object
 4   Hypertension              15000 non-null  int64
 5   Heart Disease             15000 non-null  int64
 6   Marital Status            15000 non-null  object
 7   Work Type                 15000 non-null  object
 8   Residence Type            15000 non-null  object
 9   Average Glucose Level     15000 non-null  float64
 10  Body Mass Index (BMI)     15000 non-null  float64
 11  Smoking Status            15000 non-null  object
 12  Alcohol Intake            15000 non-null  object
 13  Physical Activity         15000 non-null  object
 14  Stroke History            15000 non-null  int64
 15  Family History of Stroke  15000 non-null  object
 16  Dietary Habits            15000 non-null  object
 17  Stress Levels             15000 non-null  float64
 18  Blood Pressure Levels     15000 non-null  object
 19  Cholesterol Levels        15000 non-null  object
 20  Symptoms                  12500 non-null  object
 21  Diagnosis                 15000 non-null  object
dtypes: float64(3), int64(5), object(14)
memory usage: 2.5+ MB
None

In [ ]:
# Display basic statistics for numeric columns
print(df.describe())

         Patient ID           Age  Hypertension  Heart Disease  \
count  15000.000000  15000.000000  15000.000000   15000.000000
mean   49715.802867     54.035667      0.249000       0.502933
std    29000.656642     21.063111      0.432448       0.500008
min        1.000000     18.000000      0.000000       0.000000
25%    24562.000000     36.000000      0.000000       0.000000
50%    49448.000000     54.000000      0.000000       1.000000
75%    75112.000000     72.000000      0.000000       1.000000
max    99975.000000     90.000000      1.000000       1.000000

       Average Glucose Level  Body Mass Index (BMI)  Stroke History  \
count           15000.000000           15000.000000    15000.000000
mean              129.445209              27.474302        0.500267
std                40.487792               7.230201        0.500017
min                60.000000              15.010000        0.000000
25%                94.517500              21.160000        0.000000
50%               128.900000              27.420000        1.000000
75%               164.592500              33.720000        1.000000
max               200.000000              40.000000        1.000000

       Stress Levels
count   15000.000000
mean        5.022694
std         2.873223
min         0.000000
25%         2.540000
50%         5.050000
75%         7.520000
max        10.000000

In [ ]:
# Show unique values for categorical columns
for col in df.select_dtypes(include='object').columns:
    print(f"{col}:", df[col].unique())

Patient Name: ['Mamooty Khurana' 'Kaira Subramaniam' 'Dhanush Balan' ... 'Ivana Kaur'
 'Anvi Mannan' 'Gokul Trivedi']
Gender: ['Male' 'Female']
Marital Status: ['Married' 'Single' 'Divorced']
Work Type: ['Self-employed' 'Never Worked' 'Private' 'Government Job']
Residence Type: ['Rural' 'Urban']
Smoking Status: ['Non-smoker' 'Formerly Smoked' 'Currently Smokes']
Alcohol Intake: ['Social Drinker' 'Never' 'Rarely' 'Frequent Drinker']
Physical Activity: ['Moderate' 'Low' 'High']
Family History of Stroke: ['Yes' 'No']
Dietary Habits: ['Vegan' 'Paleo' 'Pescatarian' 'Gluten-Free' 'Vegetarian' 'Non-Vegetarian'
 'Keto']
Blood Pressure Levels: ['140/108' '146/91' '154/97' ... '157/103' '112/104' '100/69']
Cholesterol Levels: ['HDL: 68, LDL: 133' 'HDL: 63, LDL: 70' 'HDL: 59, LDL: 95' ...
 'HDL: 31, LDL: 125' 'HDL: 74, LDL: 123' 'HDL: 35, LDL: 183']
Symptoms: ['Difficulty Speaking, Headache'
 'Loss of Balance, Headache, Dizziness, Confusion' 'Seizures, Dizziness'
 ...
 'Numbness, Blurred Vision, Severe Fatigue, Blurred Vision, Difficulty Speaking'
 'Difficulty Speaking, Severe Fatigue, Headache'
 'Severe Fatigue, Numbness, Confusion, Dizziness, Loss of Balance']
Diagnosis: ['Stroke' 'No Stroke']

# **HANDLE MISSING VALUES**

In [ ]:
# Check how many missing values in each column
print(df.isnull().sum())

Patient ID                     0
Patient Name                   0
Age                            0
Gender                         0
Hypertension                   0
Heart Disease                  0
Marital Status                 0
Work Type                      0
Residence Type                 0
Average Glucose Level          0
Body Mass Index (BMI)          0
Smoking Status                 0
Alcohol Intake                 0
Physical Activity              0
Stroke History                 0
Family History of Stroke       0
Dietary Habits                 0
Stress Levels                  0
Blood Pressure Levels          0
Cholesterol Levels             0
Symptoms                    2500
Diagnosis                      0
dtype: int64

In [ ]:
# List columns with missing values
missing_cols = df.columns[df.isnull().any()]
print("Columns with missing values:", missing_cols)

# Handle numeric columns
for col in missing_cols:
    if df[col].dtype in ['float64', 'int64']:
        df[col].fillna(df[col].median(), inplace=True)
    else:
        # For categorical/text columns, fill with 'Unknown'
        df[col].fillna('Unknown', inplace=True)

# Verify missing values handled
print(df.isnull().sum())

Columns with missing values: Index(['Symptoms'], dtype='object')
Patient ID                  0
Patient Name                0
Age                         0
Gender                      0
Hypertension                0
Heart Disease               0
Marital Status              0
Work Type                   0
Residence Type              0
Average Glucose Level       0
Body Mass Index (BMI)       0
Smoking Status              0
Alcohol Intake              0
Physical Activity           0
Stroke History              0
Family History of Stroke    0
Dietary Habits              0
Stress Levels               0
Blood Pressure Levels       0
Cholesterol Levels          0
Symptoms                    0
Diagnosis                   0
dtype: int64

/tmp/ipython-input-300043481.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna('Unknown', inplace=True)

# **REMOVE DUPLICATES**

In [ ]:
# Check for duplicate rows
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

# **ENCODE CATEGORICAL VARIABLES**

In [ ]:
# List of categorical/text columns in your dataset
text_cols=['Patient Name', 'Gender', 'Marital Status', 'Work Type', 'Residence Type',
 'Smoking Status', 'Alcohol Intake', 'Physical Activity',
 'Family History of Stroke', 'Dietary Habits',
  'Symptoms', 'Diagnosis']


# Initialize LabelEncoder
le = LabelEncoder()

# Encode each categorical column
for col in text_cols:
    if col in df.columns:
        df[col] = le.fit_transform(df[col].astype(str))  # Convert to string before encoding

# Encode 'Diagnosis' column separately for correlation calculation
if 'Diagnosis' in df.columns:
    df['Diagnosis'] = le.fit_transform(df['Diagnosis'])

# Verify encoding
df.head()

,Patient ID,Patient Name,Age,Gender,Hypertension,Heart Disease,Marital Status,Work Type,Residence Type,Average Glucose Level,...,Alcohol Intake,Physical Activity,Stroke History,Family History of Stroke,Dietary Habits,Stress Levels,Blood Pressure Levels,Cholesterol Levels,Symptoms,Diagnosis
0,18153,7135,56,1,0,1,1,3,0,130.91,...,3,2,0,1,5,3.48,140/108,"HDL: 68, LDL: 133",1375,1
1,62749,5859,80,1,0,0,2,3,1,183.73,...,1,1,0,0,3,1.73,146/91,"HDL: 63, LDL: 70",3146,1
2,32145,2799,26,1,1,1,1,1,0,189.00,...,2,0,0,1,3,7.31,154/97,"HDL: 59, LDL: 95",4201,1
3,6154,5191,73,1,0,0,1,1,1,185.29,...,0,2,0,0,3,5.35,174/81,"HDL: 70, LDL: 137",4059,0
4,48973,2630,51,1,1,1,0,3,1,177.34,...,2,1,0,1,4,6.84,121/95,"HDL: 65, LDL: 68",1150,1

# **Selected Features for EDA**

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
selected_features = [
    'Age',
    'Hypertension',
    'Heart Disease',
    'Body Mass Index (BMI)',
    'Average Glucose Level',
    'Smoking Status',
    'Alcohol Intake',
    'Physical Activity',
    'Stress Levels'
]

In [ ]:
import plotly.express as px


corr_matrix = df[selected_features + ['Diagnosis']].corr()

# Interactive heatmap
fig = px.imshow(
    corr_matrix,
    text_auto=".2f",               # show correlation values
    aspect="auto",
    color_continuous_scale='RdBu_r',
    title="Interactive Correlation Heatmap of Selected Features vs Diagnosis"
)

fig.show()

In [ ]:

for feature in ['Age', 'Body Mass Index (BMI)', 'Average Glucose Level']:
    fig = px.scatter(
        df,
        x=feature,
        y='Diagnosis',
        color='Diagnosis',
        opacity=0.6,
        title=f"{feature} vs Stroke Outcome",
        labels={'Diagnosis':'Stroke Outcome'}
    )
    fig.show()

In [ ]:
categorical_features = ['Smoking Status', 'Alcohol Intake', 'Physical Activity', 'Stress Levels']

for col in categorical_features:
    fig = px.histogram(
        df,
        x=col,
        color='Diagnosis',
        barmode='group',
        title=f"{col} vs Stroke Outcome",
        labels={'Diagnosis':'Stroke Outcome'},
        opacity=0.7
    )
    fig.show()

# **processed data**

In [ ]:
# Copy original DataFrame
# -------------------------
df_processed = df.copy()
df_processed.head()

,Patient ID,Patient Name,Age,Gender,Hypertension,Heart Disease,Marital Status,Work Type,Residence Type,Average Glucose Level,...,Alcohol Intake,Physical Activity,Stroke History,Family History of Stroke,Dietary Habits,Stress Levels,Blood Pressure Levels,Cholesterol Levels,Symptoms,Diagnosis
0,18153,7135,56,1,0,1,1,3,0,130.91,...,3,2,0,1,5,3.48,140/108,"HDL: 68, LDL: 133",1375,1
1,62749,5859,80,1,0,0,2,3,1,183.73,...,1,1,0,0,3,1.73,146/91,"HDL: 63, LDL: 70",3146,1
2,32145,2799,26,1,1,1,1,1,0,189.00,...,2,0,0,1,3,7.31,154/97,"HDL: 59, LDL: 95",4201,1
3,6154,5191,73,1,0,0,1,1,1,185.29,...,0,2,0,0,3,5.35,174/81,"HDL: 70, LDL: 137",4059,0
4,48973,2630,51,1,1,1,0,3,1,177.34,...,2,1,0,1,4,6.84,121/95,"HDL: 65, LDL: 68",1150,1

# **DEFINE FEATURES AND TARGET**

In [ ]:
# Drop identifier columns from Features
cols_to_drop = ['Patient ID', 'Patient Name']
X = df_processed.drop(columns=cols_to_drop + ['Diagnosis'])  # Features
y = df_processed['Diagnosis']  # Target

# **ENCODE CATEGORICAL VARIABLES**

In [ ]:
# List of categorical/text columns to encode
text_cols=['Patient Name', 'Gender', 'Marital Status', 'Work Type', 'Residence Type',
 'Smoking Status', 'Alcohol Intake', 'Physical Activity',
 'Family History of Stroke', 'Dietary Habits',
 'Symptoms', 'Diagnosis']


le = LabelEncoder()
for col in text_cols:
    if col in X.columns:
        X[col] = le.fit_transform(X[col].astype(str))
        y = le.fit_transform(y)

In [ ]:
# Parse Cholesterol Levels into numeric columns
if 'Cholesterol Levels' in X.columns:
    X['HDL_Cholesterol'] = X['Cholesterol Levels'].apply(lambda x: int(x.split(',')[0].split(':')[1].strip()))
    X['LDL_Cholesterol'] = X['Cholesterol Levels'].apply(lambda x: int(x.split(',')[1].split(':')[1].strip()))
    X = X.drop('Cholesterol Levels', axis=1)
    X.head()

In [ ]:
# Now X and y are ready for Train/Test Split
X.head(), y[:5]

(   Age  Gender  Hypertension  Heart Disease  Marital Status  Work Type  \
 0   56       1             0              1               1          3
 1   80       1             0              0               2          3
 2   26       1             1              1               1          1
 3   73       1             0              0               1          1
 4   51       1             1              1               0          3

    Residence Type  Average Glucose Level  Body Mass Index (BMI)  \
 0               0                 130.91                  22.37
 1               1                 183.73                  32.57
 2               0                 189.00                  20.32
 3               1                 185.29                  27.50
 4               1                 177.34                  29.06

    Smoking Status  Alcohol Intake  Physical Activity  Stroke History  \
 0               2               3                  2               0
 1               2               1                  1               0
 2               1               2                  0               0
 3               2               0                  2               0
 4               0               2                  1               0

    Family History of Stroke  Dietary Habits  Stress Levels  \
 0                         1               5           3.48
 1                         0               3           1.73
 2                         1               3           7.31
 3                         0               3           5.35
 4                         1               4           6.84

   Blood Pressure Levels  Symptoms  HDL_Cholesterol  LDL_Cholesterol
 0               140/108       419               68              133
 1                146/91      2387               63               70
 2                154/97      3560               59               95
 3                174/81      3401               70              137
 4                121/95       170               65               68  ,
 array([1, 1, 1, 0, 1]))

# **SPLIT DATA INTO TRAIN AND TEST**

In [ ]:
# Split the dataset: 70% train, 30% test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# **Models**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, precision_score, recall_score, f1_score, roc_curve, auc

In [ ]:
# -------------------------
# Random Forest Classifier
# -------------------------
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# -------------------------
# Support Vector Machine
# -------------------------
svm_model = SVC(kernel='rbf', probability=True, random_state=42)

# -------------------------
# Linear Regression (for numeric prediction of stroke probability)
# -------------------------
lr_model = LinearRegression()

In [ ]:
from sklearn.preprocessing import StandardScaler

# Ensure 'Blood Pressure Levels' is processed if it still exists in X_train/X_test
# Process X_train
if 'Blood Pressure Levels' in X_train.columns:
    X_train['Systolic_BP'] = X_train['Blood Pressure Levels'].apply(lambda x: int(x.split('/')[0].strip()))
    X_train['Diastolic_BP'] = X_train['Blood Pressure Levels'].apply(lambda x: int(x.split('/')[1].strip()))
    X_train = X_train.drop('Blood Pressure Levels', axis=1)

# Process X_test
if 'Blood Pressure Levels' in X_test.columns:
    X_test['Systolic_BP'] = X_test['Blood Pressure Levels'].apply(lambda x: int(x.split('/')[0].strip()))
    X_test['Diastolic_BP'] = X_test['Blood Pressure Levels'].apply(lambda x: int(x.split('/')[1].strip()))
    X_test = X_test.drop('Blood Pressure Levels', axis=1)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)  # Fit on train
X_test_scaled = scaler.transform(X_test)        # Apply same scaling to test

In [ ]:
# Train Random Forest
rf_model.fit(X_train_scaled, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
# Train SVM
svm_model.fit(X_train_scaled, y_train)

SVC(probability=True, random_state=42)

In [ ]:
# Train Linear Regression
lr_model.fit(X_train_scaled, y_train)

LinearRegression()

In [ ]:
# Random Forest
y_pred_rf = rf_model.predict(X_test_scaled)

In [ ]:
# SVM
y_pred_svm = svm_model.predict(X_test_scaled)

In [ ]:
# Linear Regression
y_pred_lr = lr_model.predict(X_test_scaled)
y_pred_lr_class = [1 if x>=0.5 else 0 for x in y_pred_lr]

In [ ]:
print("--- Random Forest ---")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("Classification Report:\n", classification_report(y_test, y_pred_rf))

--- Random Forest ---
Accuracy: 0.4908888888888889
Confusion Matrix:
 [[1234  987]
 [1304  975]]
Classification Report:
               precision    recall  f1-score   support

           0       0.49      0.56      0.52      2221
           1       0.50      0.43      0.46      2279

    accuracy                           0.49      4500
   macro avg       0.49      0.49      0.49      4500
weighted avg       0.49      0.49      0.49      4500

In [ ]:
print("--- Support Vector Machine (SVM) ---")
print("Accuracy:", accuracy_score(y_test, y_pred_svm))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))
print("Classification Report:\n", classification_report(y_test, y_pred_svm))

--- Support Vector Machine (SVM) ---
Accuracy: 0.49755555555555553
Confusion Matrix:
 [[1254  967]
 [1294  985]]
Classification Report:
               precision    recall  f1-score   support

           0       0.49      0.56      0.53      2221
           1       0.50      0.43      0.47      2279

    accuracy                           0.50      4500
   macro avg       0.50      0.50      0.50      4500
weighted avg       0.50      0.50      0.50      4500

In [ ]:
from sklearn.metrics import mean_squared_error

print("--- Linear Regression ---")
mse = mean_squared_error(y_test, y_pred_lr)
print("Mean Squared Error:", mse)
print("Rounded Classification Accuracy:", accuracy_score(y_test, y_pred_lr_class))
print("Classification Report:\n", classification_report(y_test, y_pred_lr_class))

--- Linear Regression ---
Mean Squared Error: 0.25023725340337266
Rounded Classification Accuracy: 0.5062222222222222
Classification Report:
               precision    recall  f1-score   support

           0       0.50      0.62      0.55      2221
           1       0.52      0.40      0.45      2279

    accuracy                           0.51      4500
   macro avg       0.51      0.51      0.50      4500
weighted avg       0.51      0.51      0.50      4500

# **Final Visualization**

In [ ]:
def plot_confusion_matrix(y_true, y_pred, model_name):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.title(f'Confusion Matrix - {model_name}')
    plt.ylabel('Actual')
    plt.xlabel('Predicted')
    plt.show()

In [ ]:
# Predictions
y_pred_rf = rf_model.predict(X_test_scaled)
y_pred_svm = svm_model.predict(X_test_scaled)
y_pred_lr = lr_model.predict(X_test_scaled)
y_pred_lr_class = [1 if x>=0.5 else 0 for x in y_pred_lr]

In [ ]:
def plot_confusion_matrix_interactive(y_true, y_pred, model_name):
    cm = confusion_matrix(y_true, y_pred)
    fig = px.imshow(
        cm,
        text_auto=True,
        labels=dict(x="Predicted", y="Actual", color="Count"),
        x=[0,1],
        y=[0,1],
        color_continuous_scale='Blues',
        title=f"{model_name} - Confusion Matrix (Interactive)"
    )
    fig.show()

# Interactive Confusion Matrices
plot_confusion_matrix_interactive(y_test, y_pred_rf, "Random Forest")
plot_confusion_matrix_interactive(y_test, y_pred_svm, "SVM")
plot_confusion_matrix_interactive(y_test, y_pred_lr_class, "Linear Regression")

In [ ]:
# Linear Regression coefficients
lr_coef = lr_model.coef_

# Random Forest feature importance
rf_importance = rf_model.feature_importances_

features = X_train.columns
df_feat = pd.DataFrame({
    'Feature': features,
    'LR_Coefficient': lr_coef,
    'RF_Importance': rf_importance
})

# Interactive heatmap
fig = px.imshow(
    df_feat.set_index('Feature'),
    text_auto=".2f",
    aspect="auto",
    color_continuous_scale='RdBu_r',
    title="Feature Importance - LR & RF (Interactive)"
)
fig.show()

In [ ]:
# Model Comparison
def model_metrics(y_true, y_pred, model_name):
    return {
        "Model": model_name,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred),
        "Recall": recall_score(y_true, y_pred),
        "F1": f1_score(y_true, y_pred)
    }

metrics_list = [
    model_metrics(y_test, y_pred_rf, "Random Forest"),
    model_metrics(y_test, y_pred_svm, "SVM"),
    model_metrics(y_test, y_pred_lr_class, "Linear Regression")
]

df_metrics = pd.DataFrame(metrics_list)
print("Model Comparison:")
display(df_metrics)


best_model_name = df_metrics.sort_values(by='F1', ascending=False).iloc[0]['Model']
print(f"\nBest Model: {best_model_name}")

Model Comparison:

               Model  Accuracy  Precision    Recall        F1
0      Random Forest  0.497333   0.504189  0.448881  0.474930
1                SVM  0.483111   0.488029  0.420360  0.451674
2  Linear Regression  0.501778   0.510423  0.397543  0.446966

Best Model: Random Forest

In [ ]:
# Model Comparison (re-included for robustness against NameError)
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def model_metrics(y_true, y_pred, model_name):
    return {
        "Model": model_name,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred, zero_division=1),
        "Recall": recall_score(y_true, y_pred, zero_division=1),
        "F1": f1_score(y_true, y_pred, zero_division=1)
    }

metrics_list = [
    model_metrics(y_test, y_pred_rf, "Random Forest"),
    model_metrics(y_test, y_pred_svm, "SVM"),
    model_metrics(y_test, y_pred_lr_class, "Linear Regression")
]

df_metrics = pd.DataFrame(metrics_list)
best_model_name = df_metrics.sort_values(by='F1', ascending=False).iloc[0]['Model']


# Example: New patient data (same columns and encoding as X_train)
new_data = pd.DataFrame({
    'Age':[65, 50, 72],
    'Gender':[1,0,1],
    'Hypertension':[1,0,1],
    'Heart Disease':[0,1,0],
    'Marital Status':[1,0,1],
    'Work Type':[2,1,0],
    'Residence Type':[1,0,1],
    'Average Glucose Level':[140, 110, 180],
    'Body Mass Index (BMI)':[28.5, 24.0, 32.0],
    'Smoking Status':[1,0,1],
    'Alcohol Intake':[0,1,1],
    'Physical Activity':[1,0,0],
    'Stroke History':[0,0,1],
    'Family History of Stroke':[1,0,1],
    'Dietary Habits':[1,0,1],
    'Stress Levels':[0,1,2],
    'Symptoms':[1,0,1],
    'HDL_Cholesterol':[55,60,45],
    'LDL_Cholesterol':[120,90,160],
    'Systolic_BP':[124, 118, 150],
    'Diastolic_BP':[80, 75, 95]
})

# Ensure columns match X_train
new_data = new_data[X_train.columns]

# Scale the new data (for SVM / Linear Regression)
new_data_scaled = scaler.transform(new_data)

# Predict probability using the best model
if best_model_name == "Random Forest":
    new_prob = rf_model.predict_proba(new_data_scaled)[:,1]
elif best_model_name == "SVM":
    new_prob = svm_model.predict_proba(new_data_scaled)[:,1]
else:
    new_prob = lr_model.predict(new_data_scaled)
    # Clip to [0,1] range
    new_prob = [max(0, min(1, x)) for x in new_prob]

# Convert to class prediction using threshold 0.3
new_pred_class = [1 if p >= 0.5 else 0 for p in new_prob]

# Display results
df_new_pred = new_data.copy()
df_new_pred['Predicted_Probability'] = new_prob
df_new_pred['Predicted_Stroke'] = new_pred_class

print("\nPredicted Stroke Probability and Class for New Data:")
display(df_new_pred)

Predicted Stroke Probability and Class for New Data:

,Age,Gender,Hypertension,Heart Disease,Marital Status,Work Type,Residence Type,Average Glucose Level,Body Mass Index (BMI),Smoking Status,...,Family History of Stroke,Dietary Habits,Stress Levels,Symptoms,HDL_Cholesterol,LDL_Cholesterol,Systolic_BP,Diastolic_BP,Predicted_Probability,Predicted_Stroke
0,65,1,1,0,1,2,1,140,28.5,1,...,1,1,0,1,55,120,124,80,0.465824,0
1,50,0,0,1,0,1,0,110,24.0,0,...,0,0,1,0,60,90,118,75,0.474275,0
2,72,1,1,0,1,0,1,180,32.0,1,...,1,1,2,1,45,160,150,95,0.479110,0

In [ ]:
new_data = pd.DataFrame({
    'Age':[75],
    'Gender':[1],
    'Hypertension':[1],
    'Heart Disease':[1],
    'Marital Status':[1],
    'Work Type':[0],
    'Residence Type':[1],
    'Average Glucose Level':[200],   # Very high glucose
    'Body Mass Index (BMI)':[35.0],
    'Smoking Status':[1],
    'Alcohol Intake':[1],
    'Physical Activity':[0],
    'Stroke History':[1],
    'Family History of Stroke':[1],
    'Dietary Habits':[1],
    'Stress Levels':[5],
    'Symptoms':[1],
    'HDL_Cholesterol':[35],
    'LDL_Cholesterol':[180],         # Very high LDL
    'Systolic_BP':[160],              # High BP
    'Diastolic_BP':[100]              # High BP
})

# Ensure columns match X_train
new_data = new_data[X_train.columns]

# Scale new data
new_data_scaled = scaler.transform(new_data)

# Predict probability using best model
if best_model_name == "Random Forest":
    new_prob = rf_model.predict_proba(new_data_scaled)[:,1]
elif best_model_name == "SVM":
    new_prob = svm_model.predict_proba(new_data_scaled)[:,1]
else:
    new_prob = lr_model.predict(new_data_scaled)
    new_prob = [max(0, min(1, x)) for x in new_prob]

# Apply threshold 0.5
new_pred_class = [1 if p >= 0.5 else 0 for p in new_prob]

# Display results
df_new_pred = new_data.copy()
df_new_pred['Predicted_Probability'] = new_prob
df_new_pred['Predicted_Stroke'] = new_pred_class

display(df_new_pred)

,Age,Gender,Hypertension,Heart Disease,Marital Status,Work Type,Residence Type,Average Glucose Level,Body Mass Index (BMI),Smoking Status,...,Family History of Stroke,Dietary Habits,Stress Levels,Symptoms,HDL_Cholesterol,LDL_Cholesterol,Systolic_BP,Diastolic_BP,Predicted_Probability,Predicted_Stroke
0,75,1,1,1,1,0,1,200,35.0,1,...,1,1,5,1,35,180,160,100,0.5,1